### ISSUE TITLE
Some paths from the generated docs don´t exist for the build! macro.

### ISSUE THREAD

**Issue by kappilino** [microsoft/windows-rs#1022]
The path in the documation for `OWNER_SECURITY_INFORMATION`,  `Windows::Win32::System::Services::OWNER_SECURITY_INFORMATION` is not reachable for the build! macro. 

Is there a way to find the right path without the generated docs ? Because `Windows::Win32::Security::Authorization::SE_FILE_OBJECT` is also not reachable.

**Comment by riverar** [comment]
Looks right to me, are you on the latest crate? (0.18)

**Comment by kappilino** [comment]
Yes i use 0.18. I also tryed to build my binding crate seperate from the main programm with cargo to exclude proplems that can accure with the rust-analyzer, sometimes. The paths are directly copied from the docs.

**Comment by riverar** [comment]
I can reproduce this.
1. `git clone https://github.com/riverar/repo-b40a59d6`
2. `cargo build`

To unblock, you could widen your selection:
```rust
windows::build! {
    Windows::Win32::System::Services::*,
    Windows::Win32::Security::Authorization::*
};
```

**Comment by kennykerr** [comment]
The metadata defines these values as unscoped enum values. It basically groups these constants into types but they were never intended to be used as types (C style enums are weakly typed and often they weren't enums at all) but the build macro has to make the best of this situation. What you can do is import `SE_OBJECT_TYPE` and `OBJECT_SECURITY_INFORMATION` respectively and it will define all of the constants in the surrounding module. [This is by design](https://github.com/microsoft/windows-rs/pull/843) but I should add an FAQ for this.

**Comment by riverar** [comment]
Closing as `Windows::Win32::System::Services::OBJECT_SECURITY_INFORMATION`, et al, works.
