### ISSUE TITLE
Examples of non-trivial open source projects using windows-rs?

### ISSUE THREAD

**Issue by LGUG2Z** [microsoft/windows-rs#1029]
Is there any interest in adding links to more complex open source projects using `windows-rs` to provide developers with more real-world examples to look through and learn from?

I am the developer and maintainer of [komorebi](https://github.com/LGUG2Z/komorebi) which is built almost entirely on top of `windows-rs`, and I had absolutely 0 Windows development experience (in any language) before I started the project.

I spent a lot of time using GitHub search to look up functions exported by `windows-rs` in use in other projects whenever I got stuck (spoiler: I got stuck a lot), and I have a feeling that I'm not the only person who does this, so I think that having a list of non-trivial projects to complement the samples could help improve the new developer experience.

**Comment by kennykerr** [comment]
Thanks for sharing! That looks cool. I don't have a place for such things at the moment. I've heard rumblings about GitHub possibly adding support for Cargo package dependency tracking so that GitHub itself can track such usage and make it easily discoverable, as they do for other package managers. I'd rather put the pressure on GitHub to provide this service automatically.
