### ISSUE TITLE
Catch unwinding panics across FFI boundary 

### ISSUE THREAD

**Issue by bdbai** [microsoft/windows-rs#1061]
Currently, generated interface implementation (including callback consumption) does not catch unwinding panics. By default, when a panic occurs in user code, the thread starts unwinding all the way down to system dlls. Since [unwinding across FFI boundary](https://doc.rust-lang.org/nomicon/ffi.html#ffi-and-panics) is undefined behavior, user code invocations should be wrapped in [`catch_unwind`](https://doc.rust-lang.org/std/panic/fn.catch_unwind.html).

**Comment by kennykerr** [comment]
Yeah, I'm still trying to figure out how best to handle this. On Windows, we generally have an abort/terminate function that immediately terminates the process (e.g. [TerminateProcess](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-terminateprocess)) without unwinding in order to collect reliable crash dumps. This is distinct from "exceptions" that may unwind the stack, and we certainly don't want to allow exceptions to unwind as that is not reliable across ABI boundaries in C++ either. So ideally, we could ensure that `panic` does not unwind but if I don't know whether that is practical. 

And if `catch_unwind` is used, the question is what to do with the resulting error. I don't want it to propagate but neither do I want to simply swallow the error and lose that context.

**Comment by MrNeedHelpHere** [comment]
Do not terminate accounts have been engaged in illegal activities and police reports filed they are panicking

**Comment by bdbai** [comment]
> I don't want it to propagate

May I know the reason not to do so?

**Comment by kennykerr** [comment]
Because the ABI semantics don't allow for it. Errors must be reported via return codes. Unwinding is also not compatible across compilers and languages.

**Comment by bdbai** [comment]
Can we mimic the behavior when an exception is thrown in cppwinrt, like reporting the error via `RoOriginateLanguageException`?

**Comment by RobJellinghaus** [comment]
FWIW there is an RFC to reduce undefined behavior when unwinding across FFI boundaries, but it looks to be fairly static in the last year or so: https://github.com/rust-lang/rfcs/blob/master/text/2945-c-unwind-abi.md

**Comment by kennykerr** [comment]
Just looking again at this old issue. I think I'm going to leave this up to the implementor. I don't see what the `implement` macro can do beyond simply aborting in such cases, in which case it would be more efficient to do that declaratively:

https://doc.rust-lang.org/book/ch09-01-unrecoverable-errors-with-panic.html
