### ISSUE TITLE
Linker arguments wrong case when cross-compiling.

### ISSUE THREAD

**Issue by ke1satsu** [microsoft/windows-rs#1073]
Hi, I am attempting to cross-compile the windows-samples-rs crate to check out the features (commit 3a378f1) and I get an error while targeting x86_64-pc-windows-gnu. The linker complains about not finding KERNEL32, USER32, OLEAUT32 and OLE32. After trying to link manually I believe the reason for the errors is that the arguments are given in upper case. After swapping the arguments out to lower case the build works.

Now I'm unsure that this is actually i bug in the windows crate. Could it perhaps be related to the linking macros? Or is it rather a bug in cargo itself?

**Comment by ke1satsu** [comment]
It appears that if I change the #[link(name = "LIBNAME")] to lower case the errors go away. I'm still looking for where USER32 is set, the others were located in the src/bindings.rs file.

**Comment by ke1satsu** [comment]
So I think the remaining tweak to get the errors to go away is to modify src/macros so that the name is cast to lower case. I'm kinda new at Rust so I'm not sure what part of the macro_rules that should be corrected however.

**Comment by kennykerr** [comment]
The names come from the win32 winmd located here:

https://github.com/microsoft/windows-rs/tree/master/crates/reader/default

Do you know why the casing matters? The Windows file system is not case-specific. We could lower-case it in the metadata or in the resulting bindings, but I'd like to understand the problem a little better first.

**Comment by ke1satsu** [comment]
All right, I'll have a look!

So I am writing my crate on Linux and the mingw linker can't seem to find the libraries if they are in upper case. Sorry for not explaining this better! I've never contributed to projects before so I'm improvising as I go.

**Comment by ke1satsu** [comment]
So for instance this block:

#[link(name = "USER32")]
                        extern "system" {
                            fn MessageBoxA(
                                hwnd: super::super::Foundation::HWND,
                                lptext: super::super::Foundation::PSTR,
                                lpcaption: super::super::Foundation::PSTR,
                                utype: MESSAGEBOX_STYLE,
                            ) -> MESSAGEBOX_RESULT;
                        }
The casing in the decorator is what ends up in the linker arguments when I try to build with cargo.

**Comment by kennykerr** [comment]
Ah, this may be related to #638 but if its a simple matter of fixing the casing then we may be close. 😉 

Question, if you're building on Linux where do you get the user32.lib file to link against? 

Also, note that we are moving to using raw-dylib so that we won't have to use lib files any longer on Windows. I'm not sure how that affects cross-compiling with Linux. @ricobbe

**Comment by ke1satsu** [comment]
mingw ships with the necessary libraries! They are packed as ar-archives and on my system they exist on /usr/x86_64-w64-mingw32/lib/. So user32 for instance is named libuser32.a (all lower case).

I'm not sure how raw-dylib will impact cross-compilation on Linux but I guess that as long as the case is matching and there is a tool capable of linking the files it should work? :) It looks like mingw can handle dylibs since it can compile to mac OSX

**Comment by ricobbe** [comment]
Cross-compilation is not something I considered or tested when working on raw-dylib, unfortunately.  It's enabled or disabled based on the target triple, so theoretically it should work, but that may depend on which linker rustc uses to construct the .rlib file in this case.   It turns out that there are two slightly different formats for the import library, and rustc (via llvm) can only generate one of the formats, while certain linkers can only read the other.  (This, for instance, is why windows-gnu targets don't support raw-dylib at the moment, cross-compilation or otherwise.)

**Comment by kennykerr** [comment]
That may be a problem for raw-dylib adoption in general as many projects cross-compile. We may then end up just generating libs as winapi has been doing, although that's a very tedious process.

**Comment by kennykerr** [comment]
I'm going to close this issue in favor of #638 as this appears to be the same issue. Feel free to keep the conversation going over there.
