### ISSUE TITLE
Document how to use IntoParam inside a COM interface

### ISSUE THREAD

**Issue by saschanaz** [microsoft/windows-rs#1079]
FAQ says it's to pass arguments easier, but it's not readily straightforward to actually receive the argument. 

```rs
    // IInitializeWithStream::Initialize
    fn Initialize<'a>(
        &mut self,
        pstream: impl IntoParam<'a, IStream>,
        _grfmode: u32,
    ) -> windows::Result<()> {
        // how to access IStream from pstream and store it?
    }
```

**Comment by kennykerr** [comment]
Yes that's worthy of some explanation. Briefly, the IntoParam trait is only used when calling a function but never when implementing the function. Implementations should just use the parameter types directly.

**Comment by kennykerr** [comment]
@adnanademovic I'm not sure I understand your question. I think @saschanaz was talking about implementing a COM interface while you appear to be calling a Win32 function. Those are very different things. My point earlier was that `IntoParam` is only used when calling a function in order to provide convertibility. Ignoring the docs on how to use the function semantically, here's how you might call it mechanically:

```rust
use windows::{core::*, Win32::Devices::HumanInterfaceDevice::*, Win32::Foundation::*};

fn main() -> Result<()> {
    unsafe {
        let mut input: Option<IDirectInput8A> = None;

        DirectInput8Create(
            HINSTANCE(0),
            DIRECTINPUT_VERSION,
            &IDirectInput8A::IID,
            &mut input as *mut _ as _,
            None,
        )?;
        
        Ok(())
    }
}
```

The only real wart is the way the COM object is returned to the caller. The usual COM query return pattern doesn't apply because there is that pesky trailing parameter that defeats the natural transformation that the `windows` crate would otherwise apply.
