### ISSUE TITLE
Generated docs not linked in a visible enough manner

### ISSUE THREAD

**Issue by rylev** [microsoft/windows-rs#1114]
I've had several people ask me how to find out the namespaces that types and functions live in. While it's been easy enough to point them to [the generated docs](https://microsoft.github.io/windows-docs-rs/) it would be nice if this information were easier to find. It's currently linked in the readme, but not very clearly.

Can we figure out a way to make this more apparent?

**Comment by FreddyD-GH** [comment]
My apologies if this has been asked before in another issue, but is there any reason that finding the namespace is even necessary for Win32 APIs?  In particular, I've been using CsWin32 and because it's scoped only to the Win32 APIs, it allows you simply specify just the method or type you want without the full namespace (e.g. `CreateFile`).  When the Win32 namespaces were being changed and rearranged like crazy, this made CsWin32 far nicer to use than the Rust crate (didn't have to touch the `NativeMethods.txt` file, just had to update the usings).  Presumably the namespaces should be becoming more and more stable, so that should be less of a pain going forward, but _it still is annoying to lookup the namespaces for every single API that I'm using when it seems like a task that could be automated_.  It makes using the Rust crate take far longer to setup and get going than something like CsWin32.  In my mind, the Win32 APIs are a large enough part of the crate to justify special casing them, especially if they are generating enough questions to necessitate better documentation.

Personally, about 95% of the time that I use the docs, I am only using it to look up namespaces.  The other 5% is looking up APIs where the Rust version differs from the expected API, e.g. overloaded members.  

I don't actually have a strong opinion about requiring the namespaces, but it did always seem strange to me and it is very time consuming.  However, in the end, what I like most about this crate is that it actually works.  If that requires me to use artificial namespaces, I am fine with that.  I just wanted to throw out the idea that there could be alternative approaches rather than just changing the documentation.

**Comment by kennykerr** [comment]
There are a handful of APIs that collide if you were to generate them all in a single namespace. The Windows crate also lets you take advantage of the namespaces to generate all the APIs in a single namespace without having to name them all e.g. `Direct3D11::*`. I'm not sure how @AArnott is handling these issues.

Taking a step back though, I'm getting closer to solving #432 which should solve both the doc and the namespace problem in a more idiomatic way for Rust developers with a collection of crates that will hopefully be easier to work with in general.

**Comment by FreddyD-GH** [comment]
@kennykerr I was not suggesting to generate them in a single namespace, but rather special casing how the names are resolved by the build script.  I was assuming that you would allow either the short name or fully qualified name, so that both `CreateFile` and `Windows.Win32.Storage.FileSystem.CreateFile` would be valid.  I'm not actually sure what CsWin32 does, but in the event of a collision/conflict, you could require the fully-qualified name.  The more I think about this issue, the more I have thoughts on it, but it sounds like you think #432 might be a better solution, so maybe I'll hold off until I see how that changes the experience.

**Comment by riverar** [comment]
Consider also that the `windows` crate consumes metadata from other sources, such as the Windows App SDK, WebView2, and files directly fed in by the developer, further increasing the likelihood of collisions. That said, one could perhaps argue we could accept the naked declarations and only throw an error if ambiguity arises. 

```
error: "Initialize" is an ambiguous reference to multiple APIs. Provide the full namespace to resolve.
Windows.Win32.Security.ExtensibleAuthenticationProtocol.IAccountingProviderConf.Initialize
Windows.Win32.Security.Cryptography.Certificates.ICertificatePolicy.Initialize
... 29831 more
```

Will have to think about the value here versus the increased build macro complexity (and potentially perf hit).

**Comment by kennykerr** [comment]
Yes, having to scan each namespace for unqualified names would likely be prohibitive. 

In the long run, I expect the build macro to be a tool that is only used for more "interesting" use cases.

**Comment by FreddyD-GH** [comment]
@riverar I don't think the example you give is a good solution, mainly for the reason you mention of causing collisions (especially with additional WinMDs).  I think it would need to be explicitly-opted into.  Again, I'm not an expert on Rust build scripts and what is possible, but there is an issue that mentions attributes, so perhaps something more like this is more what I'm imagining:

```
windows::build! {
   [Win32Metadata]
   Initialize
}
```

However, as I think about it more, I think there are even better solutions out there than that.   Perf and complexity are more of a concern to me than collisions.  However, again, I'll try not to take up too much space on this issue if @kennykerr thinks are other solutions to help.

**Comment by rylev** [comment]
Can we please discuss this in a separate issue? The discussion here has almost nothing to do with the issue here.

**Comment by kennykerr** [comment]
I don't mind if you want to move the link more prominently toward the top of the readme. Not sure what else to suggest at this point.

**Comment by FreddyD-GH** [comment]
As the one who contributed most to getting off topic, I do apologize.  In addition to moving the section to the top of the readme, I would also suggest giving that section its own heading to make it more prominent/easier to find.

**Comment by kennykerr** [comment]
I have simplified the readme and made this link more prominent.

**Comment by AArnott** [comment]
> I'm not sure how @AArnott is handling these issues.

Recent versions of CsWin32 do distribute methods across multiple `PInvoke` classes defined across many namespaces. Folks can use `using static` to remove the need to mention the class in front of the method name. If there are collisions due to importing too much, C# lets you disambiguate just for the collision cases.
