### ISSUE TITLE
Suboptimal snake_case conversion in some cases

### ISSUE THREAD

**Issue by Boddlnagg** [microsoft/windows-rs#112]
The snake_case conversion as currently implemented already does a pretty good job, but there are a few edge cases where it produces suboptimal results (all the names are taken from actual WinRT method names). I have grouped them into several categories:

1) When digits are involved:
   - `CreateFrom3MFAsync` -> `create_from3mf_async` (instead of `create_from_3mf_async`)
   - `ServiceSolicitation32BitUuids` -> `service_solicitation32_bit_uuids` (instead of `service_solicitation_32_bit_uuids` or `service_solicitation_32bit_uuids`)
   - `Vertical35mmEquivalent` -> `vertical35mm_equivalent_focal_length` (instead of `vertical_35mm_equivalent_focal_length`)
   - `Square30x30Logo` -> `square30x30_logo` (instead of `square_30x30_logo`)

2) For certain proper names (we had an [issue opened about that in winrt-rust](https://github.com/contextfree/winrt-rust/issues/65)):
   - `IsJavaScriptEnabled` ->`is_java_script_enabled` (instead of `is_javascript_enabled`)
   - `IsIndexedDBEnabled` -> `is_indexed_db_enabled` (instead of `is_indexeddb_enabled`)
   - `AudioFormatWMAudioV9` -> `audio_format_wm_audio_v9` (instead of `audio_format_wmaudio_v9`, although that's debatable)

3) When interface or class names are involved (could be considered part of category 2):
   - `StartAnimationWithIAnimationObject` -> `start_animation_with_ianimation_object` (instead of `start_animation_with_ianimationobject`, although that's debatable)
   - `CreateFromIMediaSource` -> `create_from_imedia_source` (instead of `create_from_imediasource`)

4) When CamelCase names are buggy in the first place (which sadly exists):
   - `GetFileURLs` -> `get_file_ur_ls` (instead of `get_file_urls`)

To solve all these cases, I think it is required to use some kind of list of special cases (because, for example, it is not possible to decide in general whether there should be a `_` between a word and a number).

The basic idea to fix category 1 errors is to always split between words and digits, if the "word" contains more than 1 letter (so `30x30` won't be turned into `30_x_30`). Then a list of special cases is used to suppress any splitting within known names, such as `Direct3D11` (which would otherwise be turned into `direct_3d11`), or `URLs` (to fix category 4).

A fundamental question that arises is this: Is it okay to hard code a list of special cases / exceptions? It's certainly a bit fragile, because it might mean that some cases are missed, and changing the list would be a breaking change for the generated API, which seems problematic ...

By the way, the algorithm we used in winrt-rust does use a list of special cases. You can see a Rust implementation [here](https://github.com/Boddlnagg/winrt-rust/blob/82af9343c88cde639f9f08c50e4edf28d77dea3c/codegen/src/methods.rs#L27-L96) (many of the special cases there might not be needed if the algorithm would be improved in other ways, but some will certainly remain).

**Comment by kennykerr** [comment]
Thanks Patrick, categorizing the problem is very helpful! There are some that are more egregious than others, but it would be nice to have an approach that can address all issues. I really don't like hard-coded lists as I'm naturally a fan of metadata-driven tooling, but I understand how some of these would be very difficult to resolve heuristically.

So a minor concern is maintainability of a hard-coded list. A major concern is performance. There are many thousands of names that need to be converted and we need to ensure that the solution does not impact code generation performance substantially.

**Comment by kennykerr** [comment]
I just noticed that the `WifiDirect` namespace is converted to `wi_fi_direct`. Not sure if this is wrong, but somehow it feels wrong. 😉

**Comment by rylev** [comment]
In the `WiFiDirect` case, it's because the name uses `WiFi` not `Wifi`. I don't believe we'll be able to address that without an explicit special case.

**Comment by Boddlnagg** [comment]
Yep, this is essentially the same as the `JavaScript` case mentioned above (which is suboptimally converted to `java_script`).

**Comment by kennykerr** [comment]
Yes, I'm just concerned that patching these isn't very sustainable and that perhaps we should just let the original names flow through to Rust.

**Comment by kennykerr** [comment]
I'm thinking of scrapping the snake_case conversions altogether. Originally I tried snake_casing WinRT APIs but left Win32 and COM APIs alone. In practice I've found the familiarity of snake case completely outweighed by the pain of porting code or just cross referencing documentation. Given all the problems with lossy conversions and as I'm starting work on API authoring (#81), it seems like a good time to remove this and just stick faithfully to the original API names.

**Comment by robmikh** [comment]
Looking up APIs twice certainly has introduced friction (once on MSDN and again in the crate documentation to find the snake_case version). Although with time I've grown accustomed to the snake_casing, especially for APIs I'm familiar with (e.g. Windows.UI.Composition, Windows.Graphics.Capture). I personally lean towards the snake_casing since WinRT is projected in a more idiomatic way than Win32. It feels at home with the rest of Rust. But if it produces unneeded complexity, I can understand getting rid of it.

Do you have an idea for what to do with properties? I never liked the ABI's get_ and put_ prefixes, however, I guess you could do what is done now but without the snake_case transformation (e.g. AnchorPoint(..) and SetAnchorPoint(..)).

**Comment by kennykerr** [comment]
Yes, I would still preserve the shortening for "special" members (e.g. events and properties). So yes you would still have `AnchorPoint` and `SetAnchorPoint`. 

There are definitely pros and cons but the cons around snake_case are mounting and just being faithful to the original API names solves a lot of problems.

**Comment by robmikh** [comment]
Honestly, that sounds good enough for me. Being able to just look things up once on MSDN is attractive from the writing perspective.
