### ISSUE TITLE
How could I create DllMain with windows-rs?

### ISSUE THREAD

**Issue by s3pt3mb3r** [microsoft/windows-rs#1143]
I'm a beginner of rust, and even not familiar with Windows API either.
I've written a piece of code which should be the dll that can be injected to the process.
However, even though the compilation and injection went well, it did not work.

Things I want to ask:
- If you inject the dll to for example, notepad.exe, the console doesn't show up. why?
- The way i cast types. (I experimentally used mem::transmute but definitely wrong )
- What is the alternative type of LPVOID. is it *const c_void?

It'd be great if you give me some sample code which works well as dll when I compile.

```rust
use bindings::Windows::Win32::Foundation::CloseHandle;
use bindings::Windows::Win32::Foundation::BOOL;
use bindings::Windows::Win32::Foundation::HINSTANCE;
use bindings::Windows::Win32::System::Console::AllocConsole;
use bindings::Windows::Win32::System::Console::FreeConsole;
use bindings::Windows::Win32::System::LibraryLoader::DisableThreadLibraryCalls;
use bindings::Windows::Win32::System::SystemServices::DLL_PROCESS_ATTACH;
use bindings::Windows::Win32::System::Threading::CreateThread;
use bindings::Windows::Win32::System::Threading::THREAD_CREATION_FLAGS;
use std::ffi::c_void;
use std::mem;
use std::ptr;

extern "system" fn fmain(lpthreadparameter: *mut c_void) -> u32 {
    unsafe {
        AllocConsole();
    }
    loop {
        println!("hello world");
    }
    unsafe {
        FreeConsole();
    }
    0
}

fn dll_main(h_module: *mut c_void, dw_reason: u32, lp_reserved: *const c_void) -> BOOL {
    if dw_reason == DLL_PROCESS_ATTACH {
        unsafe {
            DisableThreadLibraryCalls(mem::transmute::<*mut c_void, HINSTANCE>(h_module));
            let h_thread = CreateThread(
                ptr::null_mut(),
                0,
                Some(fmain),
                h_module,
                THREAD_CREATION_FLAGS(0),
                ptr::null_mut(),
            );
            if !h_thread.is_null() {
                CloseHandle(h_thread);
            }
        }
    }
    BOOL(1)
}
```

**Comment by kennykerr** [comment]
This isn't really specific to the Windows crate. I haven't played much with DLLs in Rust but it seems you need to tell Cargo to create a DLL by adding this to your Cargo.toml file:

```
[lib]
crate-type = ["cdylib"]
```

You will then get both the DLL and the import LIB file. You then also need to use the `no_mangle` attribute on any exports:

```rust
#[no_mangle]
pub extern "system" fn SomeExport() {
    println!("SomeExport");
}

#[no_mangle]
pub extern "system" fn DllMain(
    _: *const std::ffi::c_void,
    _: u32,
    _: *const std::ffi::c_void,
) -> i32 {
    println!("DllMain");
    1
}
```

You can then take this and load it from an executable, assuming you have the necessary CRT runtime requirements. You can use `dumpbin` to figure that out. 

## WARNING 

It's rarely a good idea to implement `DllMain` as there is almost nothing you can safely do inside DllMain. I'm using `println` here but even that is likely unsafe. Even `DisableThreadLibraryCalls` from your example is problematic because modern runtimes require thread library calls.
