### ISSUE TITLE
ver.0.20.0 does not impl NULL/is_null for HWND/HINSTANCE ... (and other handles)

### ISSUE THREAD

**Issue by ZCWorks** [microsoft/windows-rs#1151]
ver.0.20.0 does not impl NULL/is_null for HWND/HINSTANCE ... (and other handles)

for example (from OUTDIR/windows.rs)

in ver.0.19.0
...
impl HWND {
                pub const NULL: Self = Self(0);
                pub fn is_null(&self) -> bool {
                    self.0 == 0
                }
            }
...

in ver.0.20.0
--> nothing

**Comment by riverar** [comment]
I can't reproduce this with 0.20.

```rust
#[test]
fn issue_1151() {
    let hwnd = HWND::default();
    assert_eq!(hwnd.is_null(), true);
}
```

Please provide more information and a repro case when filing bugs here, thanks!

**Comment by MrGibus** [comment]
@riverar
https://github.com/MrGibus/windows-rs-issue1151
Your test fails.
Can you let us know what you're doing differently?

**Comment by riverar** [comment]
Thanks for the repro! I forgot to update my bindings when I first tested this.

There were some recent changes around this so looping in @kennykerr to determine if this is a regression.

**Comment by kennykerr** [comment]
I've been trying to simplify and harmonize some of the odd edge cases and redundant options provided by the Windows crate. In particular, there is now a `Handle` trait (with an `is_invalid` method) you can use and all of the structs support the `Default` trait. So instead of `NULL` I would just use `default()` and instead of `is_null` I would use `is_invalid` which smooths over some of the weirder corner cases of the Windows API around invalid/null values. 

I have also updated all of samples, which provide more examples of all of this:

https://github.com/microsoft/windows-samples-rs/
