### ISSUE TITLE
Unclear if dependent features should be implicit or explicit

### ISSUE THREAD

**Issue by qrnch-jan** [microsoft/windows-rs#1261]
I upgraded a project to use the windows 0.23.0 crate and noticed that I was unable to access module members under `Win32::System::Diagnostics::Debug` after importing `Win32::System::Diagnostics::Debug::*`.  Checking the module's `mod.rs` under cargo's registry revealed that the members I was looking for are feature-gated behind a few features, two of which I had added for other reasons -- but I explicitly added the two others, and then it worked.

I'm wondering if the API documentation should have made it clear that these need to be explicitly added or should the features have been implicitly added when I enabled the `Win32_System_Diagnostics_Debug` feature?

**Comment by kennykerr** [comment]
This is by design to reduce build time, but I am experimenting with making this clear in the documentation. Rust doesn't have an official way for documentation to highlight what features a particular construct requires but there are ways to inject this information into the documentation, so I'm planning to do that.

**Comment by kennykerr** [comment]
The docs have now been updated to indicate which features a particular API requires:

https://microsoft.github.io/windows-docs-rs/doc/windows/

**Comment by qrnch-jan** [comment]
Excellent -- thank you!
