### ISSUE TITLE
Support Deprecated/Experimental APIs

### ISSUE THREAD

**Issue by kennykerr** [microsoft/windows-rs#1269]

**Comment by kennykerr** [comment]
I've already added a deprecated feature but there doesn't appear to be much value in adding experimental at the moment.

**Comment by riverar** [comment]
The Windows App SDK (WAS) team is stripping Experimental APIs from their metadata. Further, because the experimental channel may move APIs around, it's not going to be a straight forward codegen exercise. I think one approach we can take with the `windows-app-rs` crate is conditional compilation (e.g. `#[cfg(feature = "experimental")]`) at the source root.

At any rate, we can close this issue as there's no work to be done at this time (if ever) around the experimental attribute.
