### ISSUE TITLE
How to get HRESULT of `Win32::Networking::ActiveDirectory::IDirectorySearch::GetNextRow`?

### ISSUE THREAD

**Issue by rinfield** [microsoft/windows-rs#1371]
I apologize if I'm asking a silly question.  

I need the `HRESULT` to check whether more rows are available to search ActiveDirectory using `Win32::Networking::ActiveDirectory::IDirectorySearch`.

- [C++ example](https://docs.microsoft.com/en-us/windows/win32/api/iads/nf-iads-idirectorysearch-getnextrow)
- [ADSI Error Codes](https://docs.microsoft.com/en-us/windows/win32/adsi/generic-adsi-error-codes)

How can I get actual `HRESULT` from `Result<()>`?
It seems executing `GetNextRow()` always returns `Ok(())` even when no more rows.

https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Networking/ActiveDirectory/struct.IDirectorySearch.html#method.GetNextRow

**Comment by tim-weis** [comment]
This is the result of an issue with the Win32 metadata, that fails to contain enough information for `windows-rs` to provide a useful binding. The issue was initially reported [here](https://github.com/microsoft/win32metadata/issues/559). Since then some API's (but not all) have received the proposed `AlternateSuccessCodes` attribute (such as [`DoDragDrop`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/Ole/fn.DoDragDrop.html)). Unfortunately, `IDirectorySearch::GetNextRow` is not one of them.

As I understand it, the `AlternateSuccessCodes` attribute is in the process of getting replaced with `DllImport.PreserveSig` (see [this PR](https://github.com/microsoft/win32metadata/pull/758) for reference). It doesn't look like the Win32 metadata team is planning to invest into the temporary `AlternateSuccessCodes` solution.

The maintainers of `windows-rs` may want to bring this to the attention of the Win32 metadata team, and possibly prioritize having the issue resolved. At this time, this specific API is rendered unusable.

**Comment by rinfield** [comment]
Thank you for your explanation! I'll wait for the progress of win32metadata and windows-rs.:+1:

💭 (If it takes a long time, I wish win32metadata teams accept `AlternateSuccessCodes` solution first...)

**Comment by dqtsth** [comment]
Hi. I am blocked by issue. You can accept my solution AlternateSuccessCodes for now and later do solution better? Sorry for impatience I can not finish my project. Thank you for work and windows-rs. 👍

**Comment by rinfield** [comment]
With 0.29.0, I can now get `HRESULT` as return type. I have confirmed that the actual implementation and [documentation](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Networking/ActiveDirectory/struct.IDirectorySearch.html#method.GetNextRow) have been fixed.
