### ISSUE TITLE
`windows-bindgen` needs documentation

### ISSUE THREAD

**Issue by Alovchin91** [microsoft/windows-rs#1407]
### Motivation

It’s close to impossible to use `windows-bindgen` without documentation.

### Drawbacks

None

### Rationale and alternatives

The `Gen` class has mysterious fields with cryptic names which say nothing about what are those, how and why they should be used etc.

**Comment by kennykerr** [comment]
Its early days but yes docs for the bindgen crate are needed as I expect developers to eventually use this crate directly.

**Comment by kennykerr** [comment]
The `windows-bindgen` crate is now dramatically simpler than it was back when this issue was opened. It now also has some rudimentary function comments. Hopefully, that suffices for the time being. I still have a lot planned for `bindgen` and `metadata`, but it's pretty functional and straightforward today so I'll close this out for now. 

Related to #2396 and #2399.
