### ISSUE TITLE
Bug: TypedEventHandler is unsound

### ISSUE THREAD

**Issue by nico-abram** [microsoft/windows-rs#1409]
### Which crate is this about?

windows

### Crate version

0.29.0

### Summary

I have some private code based on https://github.com/robmikh/screenshot-rs to use the graphics capture API
It uses `Direct3D11CaptureFramePool.CreateFreeThreaded` for which MSDN says https://docs.microsoft.com/en-us/uwp/api/windows.graphics.capture.direct3d11captureframepool.createfreethreaded?view=winrt-22000
> Creates a frame pool where the dependency on the DispatcherQueue is removed and the FrameArrived event is raised on the frame pool's internal worker thread.

The FrameArrived handler is run on a worker thread. The handler is set using this method [windows::Graphics::Capture::Direct3D11CaptureFramePool::FrameArrived](https://microsoft.github.io/windows-docs-rs/doc/windows/Graphics/Capture/struct.Direct3D11CaptureFramePool.html#method.FrameArrived).
Now, the problematic part seems to be this constructor: [windows::Foundation::TypedEventHandler::new](https://microsoft.github.io/windows-docs-rs/doc/windows/Foundation/struct.TypedEventHandler.html#method.new)
```rs
pub fn new<F: FnMut(&<TSender as DefaultType>::DefaultType, &<TResult as DefaultType>::DefaultType) -> Result<()> + 'static>(invoke: F) -> Self
```
I think this ends up running on a separate thread. So I think the FnMut needs a + Send bound or something. The following triggers the assert, which I believe means this is currently unsound:
```rust
use windows::core::*;
use windows::Foundation::*;
use windows::Graphics::Capture::{Direct3D11CaptureFramePool, GraphicsCaptureItem};
use windows::Graphics::DirectX::Direct3D11::IDirect3DDevice;
use windows::Graphics::DirectX::DirectXPixelFormat;
use windows::Win32::Graphics::Gdi::{MonitorFromWindow, HMONITOR, MONITOR_DEFAULTTOPRIMARY};
use windows::Win32::Graphics::{
    Direct3D::{D3D_DRIVER_TYPE, D3D_DRIVER_TYPE_HARDWARE, D3D_DRIVER_TYPE_WARP},
    Direct3D11::{
        D3D11CreateDevice, ID3D11Device, D3D11_CREATE_DEVICE_BGRA_SUPPORT,
        D3D11_CREATE_DEVICE_FLAG, D3D11_SDK_VERSION,
    },
    Dxgi::{IDXGIDevice, DXGI_ERROR_UNSUPPORTED},
};
use windows::Win32::System::WinRT::Direct3D11::{
    CreateDirect3D11DeviceFromDXGIDevice, IDirect3DDxgiInterfaceAccess,
};
use windows::Win32::System::WinRT::{
    Graphics::Capture::IGraphicsCaptureItemInterop, RoInitialize, RO_INIT_MULTITHREADED,
};
use windows::Win32::UI::WindowsAndMessaging::GetDesktopWindow;

fn main() {
    #[derive(Clone)]
    struct NotThreadSafe(std::thread::ThreadId, std::marker::PhantomData<*const ()>);
    impl Drop for NotThreadSafe {
        fn drop(&mut self) {
            assert_eq!(self.0, std::thread::current().id())
        }
    }
    impl NotThreadSafe {
        pub fn new() -> Self {
            Self(std::thread::current().id(), std::marker::PhantomData)
        }
    }

    unsafe {
        RoInitialize(RO_INIT_MULTITHREADED).unwrap();
    }

    let d3d_device = create_d3d_device().unwrap();
    let d3d_context = unsafe {
        let mut d3d_context = None;
        d3d_device.GetImmediateContext(&mut d3d_context);
        d3d_context.unwrap()
    };
    let device = create_direct3d_device(&d3d_device).unwrap();

    let capture_interop =
        windows::core::factory::<GraphicsCaptureItem, IGraphicsCaptureItemInterop>().unwrap();

    let monitor_handle = unsafe { MonitorFromWindow(GetDesktopWindow(), MONITOR_DEFAULTTOPRIMARY) };
    let item = create_capture_item_for_monitor(&capture_interop, monitor_handle).unwrap();
    let mut item_size = item.Size().unwrap();

    let frame_pool = Direct3D11CaptureFramePool::CreateFreeThreaded(
        &device,
        DirectXPixelFormat::B8G8R8A8UIntNormalized,
        1,
        &item_size,
    )
    .unwrap();
    let session = frame_pool.CreateCaptureSession(item).unwrap();
    let test = NotThreadSafe::new();
    let handler =
        TypedEventHandler::<Direct3D11CaptureFramePool, IInspectable>::new(move |frame_pool, _| {
            drop(test.clone());
            Ok(())
        });
    frame_pool.FrameArrived(handler).unwrap();
    session.StartCapture().unwrap();
    std::thread::sleep(std::time::Duration::from_millis(5000));
}

fn create_capture_item_for_monitor(
    interop: &IGraphicsCaptureItemInterop,
    monitor_handle: HMONITOR,
) -> Result<GraphicsCaptureItem> {
    unsafe { interop.CreateForMonitor(monitor_handle) }
}

fn create_d3d_device_with_type(
    driver_type: D3D_DRIVER_TYPE,
    flags: D3D11_CREATE_DEVICE_FLAG,
    device: *mut Option<ID3D11Device>,
) -> Result<()> {
    unsafe {
        D3D11CreateDevice(
            None,
            driver_type,
            None,
            flags,
            std::ptr::null(),
            0,
            D3D11_SDK_VERSION as u32,
            device,
            std::ptr::null_mut(),
            std::ptr::null_mut(),
        )
    }
}

pub fn create_d3d_device() -> Result<ID3D11Device> {
    let mut device = None;
    let mut result = create_d3d_device_with_type(
        D3D_DRIVER_TYPE_HARDWARE,
        D3D11_CREATE_DEVICE_BGRA_SUPPORT,
        &mut device,
    );
    if let Err(error) = &result {
        if error.code() == DXGI_ERROR_UNSUPPORTED {
            result = create_d3d_device_with_type(
                D3D_DRIVER_TYPE_WARP,
                D3D11_CREATE_DEVICE_BGRA_SUPPORT,
                &mut device,
            );
        }
    }
    result?;
    Ok(device.unwrap())
}

pub fn create_direct3d_device(d3d_device: &ID3D11Device) -> Result<IDirect3DDevice> {
    let dxgi_device: IDXGIDevice = d3d_device.cast()?;
    let inspectable = unsafe { CreateDirect3D11DeviceFromDXGIDevice(Some(dxgi_device))? };
    inspectable.cast()
}

pub fn get_d3d_interface_from_object<S: Interface, R: Interface + Abi>(object: &S) -> Result<R> {
    let access: IDirect3DDxgiInterfaceAccess = object.cast()?;
    let object = unsafe { access.GetInterface::<R>()? };
    Ok(object)
}

```

I initially noticed this when I read the docs for CreateFreeThreaded and found it strange that rust allowed me to use a shared reference to this RefCell in my own code within the event handler, despite it running in another thread:
```rs
let f = Box::leak(Box::new(std::cell::RefCell::new(f)));
```
I would have expected rust to complain and make me use a Mutex.

Thanks to MaulingMonkey#1444 in the #windows-dev discord channel in the unofficial rust discord for providing the `NotThreadSafe` test type

### Expected behavior

windows-rs should not allow safe code to send !Send types from one thread to another

### Actual behavior

As it stands, windows-rs seems to allow safe code to send !Send types from one thread to another

**Comment by MaulingMonkey** [comment]
([Discord Discussion](https://discord.com/channels/273534239310479360/583054410670669833/927117613753040948))

Consequences of accepting `!Send` types in cases like this include sharing non-atomic refcounted [`std::rc::Rc`](https://doc.rust-lang.org/std/rc/struct.Rc.html)s between threads, when [`std::sync::Arc`](https://doc.rust-lang.org/std/sync/struct.Arc.html)s are required for soundness, and modifying state without a thread-safe mutex through types like `Cell<i32>` and `RefCell<String>`.  In particular, since the latter isn't guarded by an actual mutex, two threads mutably borrowing the same cell at the same time could easily lead to concurrent allocation/reallocation/mutation of the underlying pointer and length, resulting in memory corruption if you're lucky.

Even with `Direct3D11CaptureFramePool::Create` instead of `...::CreateFreeThreaded`, since `Direct3D11CaptureFramePool` is `Send`+`Sync`, it could presumably be stored in a static variable, and then a callback registered from any thread, despite those threads not being the ones to execute the callbacks.

`Direct3D11CaptureFramePool` is far from the only type to dispatch callbacks from a thread pool of some sort - it's in fact pretty pervasive for these C++/CX style APIs in my experience?  I'd be inclined to make `TypedEventHandler::new` require `Send` (and `Sync`?  and `Fn` instead of `FnMut`, as callbacks might be invoked by multiple threads simultaniously?)

While this might be overzealous for *some* specific APIs accepting `TypedEventHandler`s, I think it's likely a sensible default for the majority, and at the very least it's a safer default.  Perhaps a carefully documented **unsafe** fn `TypedEventHandler::new_local` could relax those requirements if there's a need for !Send, !Sync, FnMut callbacks...

**Comment by MaulingMonkey** [comment]
Similar issues with `WorkItemHandler::new`, `TimerElapsedHandler::new`, etc.:
```rust
// src/main.rs
use windows::Foundation::TimeSpan;
use windows::System::Threading::*;
use windows::Win32::System::WinRT::*;

use std::marker::PhantomData;
use std::thread::ThreadId;



struct NotThreadSafe(ThreadId, PhantomData<*const ()>);

impl Drop for NotThreadSafe {
    fn drop(&mut self) { assert_eq!(self.0, std::thread::current().id()) }
}

impl NotThreadSafe {
    pub fn new() -> Self { Self(std::thread::current().id(), PhantomData) }
    pub fn do_something(&self) { assert_eq!(self.0, std::thread::current().id()) }
}

fn main() {
    unsafe { RoInitialize(RO_INIT_MULTITHREADED) }.unwrap();

    let a = NotThreadSafe::new();
    ThreadPool::RunAsync(WorkItemHandler::new(move |_| { let _a = &a; Ok(()) })).unwrap();

    let b = NotThreadSafe::new();
    let _t = ThreadPoolTimer::CreatePeriodicTimer(TimerElapsedHandler::new(move |_| { b.do_something(); Ok(()) }), TimeSpan { Duration: 1 }).unwrap();

    std::thread::sleep(std::time::Duration::from_secs(5));
}
```
```toml
# Cargo.toml
[package]
name = "temp"
version = "0.1.0"
edition = "2021"

[dependencies]
windows.version = "0.29"
windows.features = [
    "Foundation",
    "System_Threading",
    "Win32_System_WinRT",
]
```
```text
PS C:\local\temp> cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target\debug\temp.exe`
thread '<unnamed>' panicked at 'thread 'assertion failed: `(left == right)`
  left: `ThreadId(1)`,
 right: `ThreadId(2)`<unnamed>', ' panicked at 'src\main.rsassertion failed: `(left == right)`
  left: `ThreadId(1)`,
 right: `ThreadId(3)`:', 13src\main.rs::2618
:note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
34error: process didn't exit successfully: `target\debug\temp.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
PS C:\local\temp> 
```

**Comment by kennykerr** [comment]
Yes, in general there is no guarantee that event handlers are called on any particular thread so these should be constrained as such.

**Comment by kennykerr** [comment]
`0.32.0` has now been published and includes this change.

**Comment by Shnatsel** [comment]
Thanks for committing and releasing the fix!

This issue has been included in the [RustSec advisory database](https://github.com/RustSec/advisory-db). It will be surfaced by tools such as [cargo-audit](https://github.com/RustSec/cargo-audit) or [cargo-deny](https://github.com/EmbarkStudios/cargo-deny) from now on.

Since it allows writing memory-unsafe code, but does not inherently create any memory unsafety itself, it will be surfaced as a warning.
