### ISSUE TITLE
Improve handling of BSTR with null pointer

### ISSUE THREAD

**Issue by vthib** [microsoft/windows-rs#1501]
I have stumbled upon some issues with the BSTR implementation while using some APIs that have a BSTR out parameter.

For example, the `IPrincipal` object has a `get_GroupId` that either fills the out parameter if the group id is set for this principal, or leaves the out parameter alone (or maybe sets it to NULL, i'm not sure):
- https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/TaskScheduler/struct.IPrincipal.html#method.GroupId
- https://docs.microsoft.com/en-us/windows/win32/api/taskschd/nf-taskschd-iprincipal-get_groupid

I would like to return this group id as an `Option<String>`, but this is impossible right now for two reasons:
- it's impossible to find out if a BSTR is null
- a BSTR is converted into a String, with the null case being coalesced with the empty case.

```
let group_id = BSTR::default();
unsafe { principal.GroupId(&mut group_id)? };
if group_id.is_null() { ... } // not possible
let group_id: String = group_id.try_into().unwrap(); // not an option
```

IMHO there are two issues to solve here:
- A `is_null` method is missing on this type
- the `TryFrom` should yield an `Option<String>` and not a `String`. This is a breaking change but the previous behavior is trivial to get back and more explicit: `bstr.try_into()?.unwrap_or(String::new)`.
- The `as_wide` method and the Clone one probably need to be adjusted as well, and maybe others. AFAICT, the Clone one is buggy as cloning an empty BSTR will return a null BSTR.

What are your opinions on this? I can do the PR if you agree on those fixes

**Comment by tim-weis** [comment]
[`BSTR`](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/automat/bstr)'s have a few surprising semantics. The particular property that [*"a `BSTR` must have identical semantics for `NULL` and for `""`"*](https://docs.microsoft.com/en-us/archive/blogs/ericlippert/erics-complete-guide-to-bstr-semantics) is why the implementation here is how it is. It's the reason why an `is_null()` method can't be written that's both in spec and meaningful at the same time.

Following that, `TryFrom` should indeed return a `String` rather than an `Option<String>`. Again, an empty string and a null pointer must behave identically, so mapping them to different `Option`-variants would be a contract violation.

The same property holds when `clone()`-ing a value: When the source is an empty string, it's both correct as well as the most efficient implementation to return a `BSTR` that holds a null pointer.

**Comment by vthib** [comment]
I see, I didn't know about this BSTR property. Thanks for the detailed answer!
