### ISSUE TITLE
windows::Foundation::TypedEventHandler::new now requires Send and D3D types do not implement it

### ISSUE THREAD

**Issue by SergejJurecko** [microsoft/windows-rs#1519]
I am trying to upgrade to 0.32.0 but I am stuck with the new type requirement for TypedEventHandler. When using Direct3D11CaptureFramePool for screen capture, you need to use IDirect3DDevice and ID3D11DeviceContext which do not implement it.

**Comment by kennykerr** [comment]
https://github.com/microsoft/windows-rs/issues/1409 is the discussion on requiring delegates to be `Send` Your issue is related to https://github.com/microsoft/win32metadata/issues/740 so that the Windows crate has some way of knowing that these are thread safe. 

As a workaround, you might be able to use [AgileReference](https://microsoft.github.io/windows-docs-rs/doc/windows/core/struct.AgileReference.html) to create a `Send` wrapper around the interface.

cc @damyanp @robmikh

**Comment by damyanp** [comment]
A trick like [this one](https://github.com/damyanp/directx-graphics-samples-rs/blob/d1b04382984b3ad1facf5f52ffd7901cc6d00488/samples/d3d12-multithreading/src/rendering.rs#L18) might help?

**Comment by SergejJurecko** [comment]
> As a workaround, you might be able to use [AgileReference](https://microsoft.github.io/windows-docs-rs/doc/windows/core/struct.AgileReference.html) to create a `Send` wrapper around the interface.

Using AgileReference compiles, unfortunately it fails at runtime for ID3D11Device:

> Error { code: 0x80040155, message: Failed to find proxy registration for IID: {DB6F6DDB-AC77-4E88-8253-819DF9BBF140}. }

> A trick like [this one](https://github.com/damyanp/directx-graphics-samples-rs/blob/d1b04382984b3ad1facf5f52ffd7901cc6d00488/samples/d3d12-multithreading/src/rendering.rs#L18) might help?

Wrapping ID3D11Device, ID3D11DeviceContext and ID3D11Texture2D using a custom type wrapper such as the one linked will compile as long as I do not use any of the internal types. As soon as I do it no longer compiles.

**Comment by kennykerr** [comment]
> any of the internal types

What do you mean by internal types?

**Comment by SergejJurecko** [comment]
Thank you @robmikh I see that your solution is the way to go. Just doing the absolute minimum in the closure.
