### ISSUE TITLE
Bug: conversion to reference with unrelated lifetime

### ISSUE THREAD

**Issue by rylev** [microsoft/windows-rs#1543]
### Which crate is this about?

windows, windows-sys

### Crate version

0.32

### Summary

While I've not yet been able to produce a crash from this, many of the `IntoParam` implementations allow going from some anonymous lifetime to a lifetime `'a` which has no relation to that anonymous lifetime. 

For example:

```rust
impl<'a> ::windows::core::IntoParam<'a, IXmlCharacterData> for &IXmlText
```

This allows turning a `&'lifetime IXmlText` (where `'lifetime` is just a name I'm giving to the anonymous lifetime) into a `&'a IXmlCharacterData`. `'lifetime` and `'a` are not related to each other. In fact `'a` could outlive `'lifetime` which would lead to a use-after-free. 

Again, I've not been able to write could that takes advantage of this to cause a crash, but I haven't really tried either. 

I believe for the large majority of cases this is fine, but we are also using `std::mem::transmute` in some cases meaning the borrow checker won't check things for us. I think the explicit lifetime is likely a safer bet. 

### Toolchain version/configuration

n/a

### Reproducible example
 
n/a

### Crate manifest

n/a

**Comment by kennykerr** [comment]
Minor clarification: this does not affect the `windows-sys` crate, which does not offer parameter conversions.

**Comment by kennykerr** [comment]
This example is actually safe since the resulting `Param` owns the copy produced by the `into_param` method:

```rust
impl<'a> ::windows::core::IntoParam<'a, IXmlCharacterData> for &IXmlText {
    fn into_param(self) -> ::windows::core::Param<'a, IXmlCharacterData> {
        ::core::convert::TryInto::<IXmlCharacterData>::try_into(self).map(::windows::core::Param::Owned).unwrap_or(::windows::core::Param::None)
    }
}
```

But that's only because WinRT always requires a cast to move from one interface to another. COM on the other hand has interface inheritance where a cast is not required and that's where the bug is. Here's an example:

```rust
impl<'a> ::windows::core::IntoParam<'a, ID2D1RenderTarget> for &ID2D1BitmapRenderTarget {
    fn into_param(self) -> ::windows::core::Param<'a, ID2D1RenderTarget> {
        ::windows::core::Param::Borrowed(unsafe { ::core::mem::transmute(self) })
    }
}
```

In this case the `ID2D1BitmapRenderTarget` vtable inherits from the `ID2D1BitmapRenderTarget` vtable so the `transmute` is safe but the lifetime is not constrained. I'll fix that.
