### ISSUE TITLE
Bug: `ToImpl::to_impl` unlikely to ever be safe

### ISSUE THREAD

**Issue by rylev** [microsoft/windows-rs#1615]
The `ToImpl::to_impl` method goes from a `&T where T: Interface` to a `&mut Self` - in other words it converts from a non-exclusive immutable reference to an exclusive mutable reference. This is very likely UB. I believe the only way that this might be correct is if the reference count is 1, but even then, I'm pretty sure the compiler is free to do optimizations that will break this at some point. 

This method is not being used in a lot of places. What is it for, and can it simply be removed? If we really need a conversion from an interface to it's underlying implementation, perhaps a `(&T) -> &Self` would be a more reasonable signature.

**Comment by kennykerr** [comment]
I'm very open to a different implementation. The `ToImpl` trait serves a very specific role and if we can accomplish that in a safer way, that should be all good. 

Often a COM/WinRT component will be handed a COM interface pointer that only the component implements. `Windows.UI.Composition` is a good example of this. It is up the to the component to determine whether this is in fact the case. For example, WinRT has metadata that guarantees that an interface has an exclusive implementation. For COM, an implementation might query for a private interface before determining that it is in fact exclusive. 

Once that determination has been made, the component needs some way to cast from the COM interface pointer to the implementation in order to gain access to whatever internals it needs.

**Comment by rylev** [comment]
An additional thing we can do as suggested by @rpjohnst is to add a `get_mut` method which returns a mutable reference to the underlying implementation if the ref count is 1 (meaning the interface has exclusive access to the underlying implementation).
