### ISSUE TITLE
DragQueryFileW doesn't write into a vector

### ISSUE THREAD

**Issue by timleg002** [microsoft/windows-rs#1686]
I have setup my application to accept dropped files, which I implemented via the WM_DROPFILES message. This code doesn't write anything into vector, I don't know why.

```rust
let mut filename_bytes = vec![]; // TODO: Doesn't work if this is a Vec<u16>, fix!

unsafe { 
   DragQueryFileW(hdrop, 0, filename_bytes.as_mut_slice());
}

println!("{:#?}",filename_bytes);
    
let filename = utf16_to_string(filename_bytes.to_vec())?;
```

However, when I change the vector `Vec<u16>` to an array `[u16; 256]`, the problem is fixed:
```rust
let mut filename_bytes = [0; 256]; // TODO: Doesn't work if this is a Vec<u16>, fix!

unsafe { 
   DragQueryFileW(hdrop, 0, filename_bytes.as_mut_slice());
}

println!("{:#?}",filename_bytes);
    
let filename = utf16_to_string(filename_bytes.to_vec())?;
```

And some bytes are successfully printed out. Could anyone point me in the right direction, as to why this is happening? Maybe this is a thing I haven't understood with Rust, but this shouldn't happen?

**Comment by Nerixyz** [comment]
`DragQueryFileW` expects a buffer that it can write to as `lpszfile` and it needs to know how much it can write to the buffer. It does this through the slice.

In Rust, slices basically are a memory-location (a start) and a length, basically a view into some data. If it's a mutable slice, then you can change the items of the slice. A `Vec` is a dynamic heap allocation of a certain length where you can add and remove items. If you give out a slice of the vector, then you give out a view into the vector where the length of the slice is the length of the vector. Notably, you _can't_ add items to the slice or remove some, however you _can_ change items (in the case of `&mut`).

In your first snippet, you initialize `filename_bytes` as a `vec![]`. This creates _an empty vector_. So a slice of this vector will be of length 0. Now if you call `DragQueryFileW`, you're basically telling it: "Give me zero bytes of the filename".

In your second snippet, `filename_bytes` is an array of length 256. There, if you give out a slice, it will have the length of your array (256), so you get the expected filename. 

Now, to make it work with a `Vec`, you need to make the vector as big as you want the buffer to be. If you initialize `filename_bytes` as `vec![0; 256]`, you'll get the expected result, since the vector has enough elements.

Though if you already know the size, you should use an array, since you don't need to dynamically resize the buffer.
