### ISSUE TITLE
`IntoParam` should support alloc-free conversions where possible

### ISSUE THREAD

**Issue by kennykerr** [microsoft/windows-rs#1757]
It should for example be possible to implement `IntoParam<PCWSTR>` for `HSTRING` and `&HSTRING` without any allocations since `HSTRING` always represents a null terminated wide string, but this is hard to express with the existing definition of `Param` and `IntoParam`.

**Comment by ryancerium** [comment]
I've been thinking on this for a while, and I just want to check if I'm understanding.

I think `IntoParam<PCWSTR> for &HSTRING` is easy because you can just use the `WindowsGetStringRawBuffer` function in the `impl`.  With a little bit of hand-waving, something like this:

```rust
impl<'a> IntoParam<'a PCWSTR> for &HSTRING {
  fn into_param(self) -> Param<'a, PCWSTR> {
    Param::Borrowed(PCWSTR(WindowsGetStringRawBuffer(self)))
  }
}
```

`IntoParam<PCWSTR> for HSTRING` needs to take ownership of the `HSTRING` and put it in the resulting `Param<PCWSTR>` object, but the `Param<PCWSTR>` doesn't have a place to hold the `HSTRING` since it's supposed to hold `PCWSTR` objects.

Could you make `Abi` into a generic type with a `DstT` generic parameter?  Then you could have an `impl Abi<PCWSTR> for HSTRING`?  I think that would require something like `Param<SrcT, DstT>` to actually hold the `HSTRING` for the duration of the call.

**Comment by kennykerr** [comment]
Closing in favor of #1811.
