### ISSUE TITLE
Idea: Link to MS Docs from the documentation

### ISSUE THREAD

**Issue by mbartlett21** [microsoft/windows-rs#1763]
I would like the Microsoft docs to be linked from the Rust documentation at microsoft.github.io/windows-docs-rs

E.g:

https://microsoft.github.io/windows-docs-rs/doc/windows/Web/Http/struct.HttpClient.html should have a link to https://docs.microsoft.com/en-us/uwp/api/Windows.Web.Http.HttpClient

**Comment by kennykerr** [comment]
Yes, I have wanted to include such links but don't have a reliable way for the bindgen crate to infer the links.

https://github.com/microsoft/win32metadata/issues/865

**Comment by mikebattista** [comment]
The links you need for this are now captured in the `[Documentation]` attribute in the latest metadata release.

**Comment by kennykerr** [comment]
I was chatting with the @stevewhims (from the docs team) and the URLs in the metadata are already out of date and even the latest variety are not guaranteed to work indefinitely so I think I'll just close this issue as I don't want to embed URLs into Rust docs since those docs are then archived indefinitely and can't be updated.

**Comment by kennykerr** [comment]
Currently, the metadata seems to use `docs.microsoft.com` whereas the docs team has since transitioned to `learn.microsoft.com` and while redirects sometimes work, this is not guaranteed.

**Comment by mikebattista** [comment]
That's an easy fix.
