### ISSUE TITLE
Bug: Conversion from windows::core::Error to std::io::Error changes the error code

### ISSUE THREAD

**Issue by vthib** [microsoft/windows-rs#1807]
### Which crate is this about?

windows

### Crate version

0.37.0

### Summary

Conversion from a `windows::core::Error` to a `std::io::Error` messes up the error code because it is truncated to 2 bytes only:

https://github.com/microsoft/windows-rs/blob/0.37.0/crates/libs/windows/src/core/error.rs#L91=

This is bothersome, some API calls can return error codes that are bigger than 65536, and the conversion transforms the error into another error entirely.

For example, a call to `FilterReplyMessage` can return `ERROR_FLT_NO_WAITER_FOR_REPLY`, which is `0x801F0020`. Conversion to `std::io::Error` generates an error code `0x20`, which is `ERROR_SHARING_VIOLATION`.

What is the purpose of this truncation? Shouldn't the `io::Error` just use the i32 code as is without any modification?

### Reproducible example

```rust
use windows::core::Error;
use windows::Win32::Foundation::ERROR_FLT_NO_WAITER_FOR_REPLY;

fn main() {
    // Lets imagine I call a windows function such as `FilterReplyMessage`, that returns an error:
    let error = Error::new(ERROR_FLT_NO_WAITER_FOR_REPLY, Default::default());
    dbg!(&error);
    println!("initial error: {}", &error);

    let io_error: std::io::Error = error.into();
    dbg!(&io_error);
    println!("after cast into io::Error: {}", &io_error);
}
```

Output:

```
[src/main.rs:7] &error = Error {
    code: 0x801F0020,
    message: No waiter is present for the filter's reply to this message.
    ,
}
initial error: No waiter is present for the filter's reply to this message.

[src/main.rs:11] &io_error = Os {
    code: 32,
    kind: Uncategorized,
    message: "The process cannot access the file because it is being used by another process.",
}
after cast into io::Error: The process cannot access the file because it is being used by another process. (os error 32)
```

### Crate manifest

```
[package]
edition = "2021"
name = "windows-issue-1807"
version = "0.1.0"

[dependencies]
windows = { version = "0.37", features = [ "Win32_Foundation" ] }
```

### Expected behavior

Conversion to `std::io::Error` should not change the error code

### Actual behavior

A `ERROR_FLT_NO_WAITER_FOR_REPLY` error becomes a `ERROR_SHARING_VIOLATION` error when converted to `std::io::Error`.

**Comment by riverar** [comment]
@vthib Can you restore and complete the reproducible example section of your issue?

**Comment by vthib** [comment]
Yes, I have updated the issue with an example

**Comment by kennykerr** [comment]
The `windows::core::Error` stores an `HRESULT`. Not every `HRESULT` maps to a Win32 error code. Those that do must fall within 16 bits and use the Win32 facility code.

https://en.wikipedia.org/wiki/HRESULT

In your example, `ERROR_FLT_NO_WAITER_FOR_REPLY` is an `HRESULT` rather than a Win32 error code and is not using the Win32 facility code so cannot be converted into a Win32 error code. The `From` implementation doesn't check the facility code. Doing so would require a `TryFrom` implementation, but I'm not sure whether that would support the `?` conversion automatically.

**Comment by ChrisDenton** [comment]
Could you not simply pass along the `HRESULT` as-is if it's not a Win32 error code?

**Comment by kennykerr** [comment]
[from_raw_os_error](https://doc.rust-lang.org/std/io/struct.Error.html#method.from_raw_os_error) doesn't say what kind of error code it expects so I'm not sure what would happen if you started feeding it `HRESULT` values, but I guess that wouldn't be any "worse" than the current truncation. We could check the facility code and only mask for Win32 error codes, otherwise you get the full `HRESULT` value.

**Comment by ChrisDenton** [comment]
`std::io::Error` can handle `HRESULT`s. Well I mean it doesn't really understand them but they can be passed through and display *should* print an error message correctly. IIRC this must work to some degree because `GetLastError` can, potentially, contain any type of error.

**Comment by vthib** [comment]
Yes, `last_os_error` uses `GetLastError` and there are afaict no constraint on the "raw" value that can be set in an `io::Error`. So IMHO passing the raw value as-is would be best.

If not, I would suggest removing the `From` implementation or replacing it with a `TryFrom` and documenting that the conversion only handles WIN32 error codes. The `From` conversion that modifies the error code is very surprising (and in my case, took me several hours of debugging to understand that a `?` error rethrow modified the original error code).

**Comment by riverar** [comment]
> IIRC this must work to some degree because `GetLastError` can, potentially, contain any type of error.

If we're talking about Win32 GetLastError, no, this only returns system error codes (not HRESULTs). Or did I misunderstand your comment?

**Comment by riverar** [comment]
Because can't reasonable infer what a developer wants here, I recommend we remove all implicit conversion between `windows::core::Error` and `std::io::Error`

**Comment by ChrisDenton** [comment]
> If we're talking about Win32 GetLastError, no, this only returns system error codes (not HRESULTs). Or did I misunderstand your comment?

See [`SetLastError`](https://docs.microsoft.com/en-us/windows/win32/api/errhandlingapi/nf-errhandlingapi-setlasterror). And in practice I've definitely seen at least `NTSTATUS` codes and nothing prevents it from containing `HRESULT`s.

**Comment by kennykerr** [comment]
We could simply implement `From` as follows (no masking):

```rust
impl core::convert::From<Error> for std::io::Error {
    fn from(from: Error) -> Self {
        Self::from_raw_os_error(from.code.0)
    }
}
```

I confirmed this works and `std::io::Error` is quite happy with `HRESULT` values, as others have noted. This might just be slightly confusing because some underlying API might return a Win32 error code but since `windows::core::Error` stores an `HRESULT`, the Win32 error code would always be transformed into an `HRESULT` as follows:

```rust
// Starting with WIN32_ERROR...
let win_error: windows::core::Error = ERROR_INVALID_DATA.into();
let std_error: std::io::Error = win_error.into();
assert_eq!(std_error.raw_os_error().unwrap(), ERROR_INVALID_DATA.to_hresult().0);
assert_eq!(format!("{}", std_error), "The data is invalid. (os error -2147024883)");

// Starting with HRESULT...
let win_error: windows::core::Error = E_INVALIDARG.into();
let std_error: std::io::Error = win_error.into();
assert_eq!(std_error.raw_os_error().unwrap(), E_INVALIDARG.0);
assert_eq!(format!("{}", std_error), "The parameter is incorrect. (os error -2147024809)");
```

Here `ERROR_INVALID_DATA` is actually `13` but turning that into an `HRESULT` becomes `-2147024883`, but at least `std::io::Error` and `windows::core::Error` contain the same value.

Alternatively, we can update `From` as follows:

```rust
impl core::convert::From<Error> for std::io::Error {
    fn from(from: Error) -> Self {
        let mut code = from.code.0;
        if ((code >> 16) & 0x7FF) == 7 {
            code = code & 0xFFFF;
        }
        Self::from_raw_os_error(code)
    }
}
```

The conversion looks as follows:

```rust
// Starting with WIN32_ERROR...
let win_error: windows::core::Error = ERROR_INVALID_DATA.into();
let std_error: std::io::Error = win_error.into();
assert_eq!(std_error.raw_os_error().unwrap(), ERROR_INVALID_DATA.0 as _);
assert_eq!(format!("{}", std_error), "The data is invalid. (os error 13)");

// Starting with HRESULT...
let win_error: windows::core::Error = E_INVALIDARG.into();
let std_error: std::io::Error = win_error.into();
assert_eq!(std_error.raw_os_error().unwrap(), ERROR_INVALID_PARAMETER.0 as _);
assert_eq!(format!("{}", std_error), "The parameter is incorrect. (os error 87)");
```

Now the original `HRESULT` turns into a Win32 error code because `E_INVALIDARG` happens to use a Win32 facility code. We'd also have to deal with `NTSTATUS`, so this gets complicated and potentially confusing. 

So, I'm inclined to think we should just pass the same error code across and not try to be overly clever:

```rust
impl core::convert::From<Error> for std::io::Error {
    fn from(from: Error) -> Self {
        Self::from_raw_os_error(from.code.0)
    }
}
```

**Comment by ChrisDenton** [comment]
The advantage of converting to a Win32 error is that [`std::io::Error::kind()`](https://doc.rust-lang.org/std/io/struct.Error.html#method.kind) will be set to the appropriate [`ErrorKind`](https://doc.rust-lang.org/std/io/enum.ErrorKind.html) if it's an error that stdlib has a mapping for. But, as you say, that may not be worth the trade-offs.

**Comment by kennykerr** [comment]
Have a look at this: #1809
