### ISSUE TITLE
Bug: Class not registered (IGraphBuilder)

### ISSUE THREAD

**Issue by Zerowalker** [microsoft/windows-rs#1851]
### Crate version

0.38.0

### Summary

I can't create an instance of IGraphBuilder, it gives the error "class is not registered".

### Toolchain version/configuration

Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\dev\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-gnu
stable-x86_64-pc-windows-msvc (default)
nightly-i686-pc-windows-msvc
nightly-x86_64-pc-windows-msvc

installed targets for active toolchain
--------------------------------------

arm-unknown-linux-gnueabihf
armv7-unknown-linux-gnueabihf
i686-pc-windows-msvc
x86_64-pc-windows-gnu
x86_64-pc-windows-msvc
x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.61.0 (fe5b13d68 2022-05-18)

### Reproducible example

```rust
use std::ptr::null_mut;

use windows::{
    core::Interface,
    Win32::{
        Media::DirectShow::{IFilterGraph, IGraphBuilder},
        System::Com::{CoCreateInstance, CoInitializeEx, CLSCTX_INPROC_SERVER, COINIT},
    },
};

fn main() {
    unsafe { CoInitializeEx(null_mut(), COINIT::default()) }.unwrap();
    let _: IGraphBuilder =
        unsafe { CoCreateInstance(&IFilterGraph::IID, None, CLSCTX_INPROC_SERVER) }.unwrap();
}
```

### Crate manifest

```toml
[dependencies]
[target.'cfg(windows)'.dependencies]
windows = {version = "0.38.0", features = [
  "alloc",
  "Data_Xml_Dom",
  "Win32_System_Com",
  "Win32_Media_DirectShow",
  "Win32_Foundation",
]}
```

### Expected behavior

an instance of IGraphBuilder is created.

### Actual behavior

IGraphBuilder fails to be created.

### Additional comments

Hopefully i didn't miss something obvious, i tried this based on an older c++ project.
And looking at the documentation it should work just fine as well:  https://docs.microsoft.com/en-us/windows/win32/directshow/building-graphs-with-the-capture-graph-builder

I am guessing i am either calling CoCreateInstance wrong, or it's using the wrong CLSID.

**Comment by tim-weis** [comment]
`IFilterGraph::IID` is the interface ID. It identifies the API surface of any given COM interface. Since you are trying to instantiate a particular COM object, you'll need to pass the class ID instead. A quick search through the [documentation](https://microsoft.github.io/windows-docs-rs/doc/windows/index.html) didn't produce any hits for [`CLSID_FilterGraph`](https://microsoft.github.io/windows-docs-rs/doc/windows/?search=CLSID_FilterGraph), so you will have to declare it yourself, e.g.

```rust
fn main() {
    unsafe { CoInitializeEx(null_mut(), COINIT::default()) }.unwrap();
    let clsid = ::windows::core::GUID::from_u128(0xe436ebb3_524f_11ce_9f53_0020af0ba770);
    let _: IGraphBuilder =
        unsafe { CoCreateInstance(&clsid, None, CLSCTX_INPROC_SERVER) }.unwrap();
}
```

The ID was taken from the *uuids.h* header file of the Windows SDK.

I guess this is an issue that should be raised with the Win32Metadata project. In version 23.0.2-preview of the metadata the `CLSID_FilterGraph` constant is absent. Unless there's a specific reason why those GUIDs aren't in the metadata one of the maintainers of this repo might want to move this issue over.

**Comment by riverar** [comment]
@tim-weis beat me to a response 😄. The missing CLSID slowed me down. I filed an issue on the win32metadata side to get this fixed in the SDK/metadata.

**Comment by Zerowalker** [comment]
Ah, i get really confused by the IID / CLSID stuff, glad the "issue" lead somewhere even though it wasn't what i thought!
Thanks for the quick responses:)
