### ISSUE TITLE
DragQueryFileW and Others: Confusing (Wrong?) API

### ISSUE THREAD

**Issue by mattelkinsTC** [microsoft/windows-rs#1902]
I wasn't sure whether this was a bug report, feature request, or just commentary, so I opted for a blank issue. Apologies if that is incorrect.

DragQueryFileW and some other APIs are defined in MSDN as taking a string pointer (LPWSTR) and length (UINT); these are essentially out buffers. Providing NULL to these APIs is semantic: it is documented as signaling a request for the requisite buffer length. When attempting to upgrade from windows crate 0.28 to 0.37 I noticed that at some point the API had changed from taking a PWSTR and length to taking a `&mut [u16]`. This meant there was no documented possibility of supplying NULL to query the length.

Digging through the code, however, I found that the crate translated an empty slice to a NULL, so the operation was still possible as long as I was willing to rely on implementation detail rather than documented behavior. I would suggest that if this API is sustained, that something be done to document it so that a user can feel comfortable relying on it.

It does also mean that it is effectively impossible to supply a 0-length (but not NULL) buffer to the function, which was possible prior to this change. I will grant that in the specific case of DragQueryFileW that isn't a big deal because such an argument isn't very meaningful. That said, it is behavior that deviates from MSDN. I also seem to recall noticing other APIs which were similarly changed (I apologize for not taking better note of which ones at the time); it may be that for others a 0-length non-NULL buffer makes sense.

An additional minor note: I also noticed that when converting the slice to the pointer and length for the underlying Win32 API, the length was cast in an unchecked fashion from usize to u32. If a buffer size larger than u32::MAX is supplied, it would be silently truncated. This is almost certainly a degenerate condition (at least in the specific case of DragQueryFileW), but it does creates the possibility of more behavior deviating from MSDN. For example, if a 64-bit usize of value u32::MAX + MAX_PATHis supplied (probably as a consequence of some other bug), it would be truncated to just length MAX_PATH and the API might succeed where otherwise it would have failed. This issue is hidden by the change to using a slice; in 0.28 the length was a u32, so the using code got to make the casting decision. I would suggest that if this API is sustained, the limitation in slice length is documented (and possibly an assert! or debug_assert! added) so a user knows they need to ensure the precondition.

Thanks for your time and attention!

**Comment by kennykerr** [comment]
Thanks for the feedback. The `windows` crate aims to provide more idiomatic bindings to the Windows API and uses the metadata provided by the Windows API to do that. The `windows-sys` crate, on the other hand, provides the lowest-level raw bindings to Windows APIs without any translation. If that's what you prefer, then go with the `windows-sys` crate. 

In particular, the metadata for `DragQueryFileW` looks as follows:

```C#
[DllImport("SHELL32", ExactSpelling = true, PreserveSig = false)]
[SupportedOSPlatform("windows5.1.2600")]
public static extern uint DragQueryFileW([In] HDROP hDrop, [In] uint iFile, [Optional][Out][NativeArrayInfo(CountParamIndex = 3)] PWSTR lpszFile, [In] uint cch);
```

These attributes are derived directly from the Windows API and how it is documented, defined, and implemented to behave. As you can see, there is an explicit relationship between the third and fourth parameters. That is what the `windows` crate now models with a slice. 

If you discover a bug, open an issue with a repro and we can get it fixed. Otherwise, this is by design. If you prefer not to have this abstraction, this same function is defined by the `windows-sys` crate without any translation, [as you can see here](https://docs.rs/windows-sys/latest/windows_sys/Win32/UI/Shell/fn.DragQueryFileW.html).
