### ISSUE TITLE
Feature request: GetGuiResources should be  Result<u32>  or Result<Option<u32>> if possible

### ISSUE THREAD

**Issue by Zerowalker** [microsoft/windows-rs#1920]
### Motivation

Documentation specifies:
```
Return value
If the function succeeds, the return value is the count of handles to GUI objects in use by the process. If no GUI objects are in use, the return value is zero.

If the function fails, the return value is zero. To get extended error information, call [GetLastError](https://docs.microsoft.com/en-us/windows/desktop/api/errhandlingapi/nf-errhandlingapi-getlasterror).
```

So thinking something like this:

```rust
match unsafe { GetGuiResources(GetCurrentProcess(), GR_GDIOBJECTS) } {
        0 => {
            let err = windows::core::Error::from_win32();
            if err.code().is_ok() {
                Ok(0)
            } else {
                Err(err)
            }
        }
        o => Ok(o),
    }
```

### Drawbacks

It might not be feasible

### Rationale and alternatives

It would make things safer, similar to how other functions behaves.

**Comment by kennykerr** [comment]
Invalid values that might be used to determine whether a call failed are tied to a handle type in the win32 metadata but since this function simply returns a `u32` count, that's not likely to be supported. You could request such a feature from the win32 metadata repo, but it seems like a bit of an edge case that may not be worthwhile worrying about.

**Comment by kennykerr** [comment]
My preference would be to have the invalid values associated with the function rather than the type so we can get out of the business of inventing all kinds of odd return types, but the metadata would need to be overhauled for that.

**Comment by Zerowalker** [comment]
You mean that in win32 metadata you don't really specify the information to the function, but the return type?
If so then `your preference` means it would instead be (able) to be tied to the function instead?

If so then that's how i thought it was possible to do and i gives it my badge of approval;)

**Comment by tim-weis** [comment]
The actual contract for [`GetGuiResources`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getguiresources) is more complex than that. Consider the following code:

```rust
use windows::Win32::{
    Foundation::GetLastError,
    System::Threading::{GetCurrentProcess, GetGuiResources, GR_GDIOBJECTS},
};

fn main() {
    let cnt = unsafe { GetGuiResources(GetCurrentProcess(), GR_GDIOBJECTS) };
    let err = unsafe { GetLastError() };
    println!("GDI resources: {} (error: {:?})", cnt, err);
}
```

which produces the following output on my system:

```none
GDI resources: 0 (error: WIN32_ERROR(127))
```

Since this is a command line application a GDI count of zero is expected. The error code, however, is not. What's missing? The part that's not spelled out in the documentation: Clients need to reset the error code prior to calling this API.

The fixed version

```rust
use windows::Win32::{
    Foundation::{GetLastError, SetLastError, ERROR_SUCCESS},
    System::Threading::{GetCurrentProcess, GetGuiResources, GR_GDIOBJECTS},
};

fn main() {
    unsafe { SetLastError(ERROR_SUCCESS) };
    let cnt = unsafe { GetGuiResources(GetCurrentProcess(), GR_GDIOBJECTS) };
    let err = unsafe { GetLastError() };
    println!("GDI resources: {} (error: {:?})", cnt, err);
}
```

prints the expected result:

```none
GDI resources: 0 (error: WIN32_ERROR(0))
```

So there's an extra pre-condition here. Encoding that in metadata would seem trivial. The hard part that's left is coming up with a proposition for a way to encode *arbitrary* pre- and post-conditions, plus the unsolved problem of how to convince the Win32metadata team that contracts are associated with functions, not types.

As much as I'd like to see the metadata become more universally useful, I understand that getting any of those changes through would be an insane uphill battle.

**Comment by Zerowalker** [comment]
Oh shouldn't that be added in the documentation?
Though perhaps rare it's clearly going to say something is wrong even though it's not.

**Comment by kennykerr** [comment]
There's a github repo for the docs.

<img width="980" alt="image" src="https://user-images.githubusercontent.com/9845234/180019302-c725d234-c460-4a1a-b215-d60fded33640.png">

There's only so much the metadata and the `windows` crate can and should do here. The docs should certainly be clear, but higher-level libraries can and should focus on providing better abstractions for specific APIs like this. The `windows` crate does not attempt to make every API bulletproof.

**Comment by Zerowalker** [comment]
@tim-weis  Will you post the issue at Github, otherwise I can and provide what you described.

@kennykerr I understand it's not meant to be a jack of all trades so to speak.
I must say I find it hard to know when something fits the aspect of the project (or is appropriate in the metadata).
As it's kind kinda obscure (in my eyes), `windows-sys` being the `winapi-rs` version from Microsoft if you will.
But `windows-rs` is a layer above that where it certainly makes some things "Safe" or "Safer",
but I can't tell what it's willing to do to achieve that and what's too much and should be done by a higher level crate etc.

**Comment by tim-weis** [comment]
@Zerowalker You cannot file an issue against the [docs repo](https://github.com/MicrosoftDocs/sdk-api). It only allows you to create PR's. To author one you'd need source access to verify that the documented contract matches the implementation. Lacking that I hit the :thumbsdown: button instead, and left feedback. I don't know where that winds up.

**Comment by kennykerr** [comment]
It's certainly somewhat subjective. I will try to find some time to articulate this more clearly in an FAQ.

**Comment by kennykerr** [comment]
To be fair, many APIs have preconditions not explicitly spelled out in the docs. Calling such APIs assumes some knowledge of how the API works in context and trying to cover all preconditions in a wrapper library isn't practical as it can pessimize knowledgeable callers or even produce invalid code in some cases.
