### ISSUE TITLE
What happens if a funtion defined in `windows_sys` returns type `i32` but win32 docs say it can return `NULL`?

### ISSUE THREAD

**Issue by sn99** [microsoft/windows-rs#1948]
I might be overthinking this but is there a guarantee that the check `handle == 0` always hold in case of returned `NULL` values for `windows_sys`?

The function in question is [OpenProcess](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/Threading/fn.OpenProcess.html#) and returns type [HANDLE](https://docs.rs/windows-sys/latest/windows_sys/Win32/Foundation/type.HANDLE.html#). The same in `windows` returns type `Option<Handle>` while should be easy to evaluate in case of `NULL` or no_value. The official documentation(win32docs) says that the function can [return a `NULL`](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-openprocess) value.

**Comment by tim-weis** [comment]
The [`OpenProcess`](https://docs.rs/windows-sys/latest/windows_sys/Win32/System/Threading/fn.OpenProcess.html) function in the `windows-sys` crate indeed returns a value of type [`HANDLE`](https://docs.rs/windows-sys/latest/windows_sys/Win32/Foundation/type.HANDLE.html). `HANDLE` is a simple type alias for `isize`, and the expression `handle == 0` will always evaluate to `true` in case the API returns a value of zero.

The Win32 API [documentation](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-openprocess) calls the value `NULL` because `HANDLE` is actually a `void*` in the C header files. C requires that [`NULL`](https://en.cppreference.com/w/c/types/NULL) must be *"an integer constant expression with the value 0"*. The expression `NULL == 0` is always `true`.

**Comment by sn99** [comment]
> Return value
> If the function succeeds, the return value is an open handle to the specified process.
> If the function fails, the return value is NULL. To get extended error information, call [GetLastError](https://docs.microsoft.com/en-us/windows/desktop/api/errhandlingapi/nf-errhandlingapi-getlasterror).

So it won't be an issue to exit the code early if `HANDLE == 0` is returned right?

**Comment by tim-weis** [comment]
I'm guessing this is asking about resource management obligations. If that is true, then if `OpenProcess` returned a value that is equal to `0`, there aren't any strings attached. There's an *opportunity* to call `GetLastError`, but you are free to exit the current scope without having to perform any kind of cleanup regarding this resource.

If the current scope is holding on to resources successfully claimed previously, then those resources still need to be released. `windows-sys` doesn't provide automatic resource management. It faithfully represents the C API, including manual resource management.

In case I completely missed what you were asking about, could you provide a minimal code sample to illustrate the issue?

**Comment by sn99** [comment]
Ah, I got it, thanks for the help, also someone pointed me to [is_invalid](https://raw.githubusercontent.com/microsoft/windows-rs/master/crates/libs/windows/src/Windows/Win32/Foundation/mod.rs) of handle from `windows`. I just realised that the documentation provided in the link and one on docs.rs have a few definitions missing and no `jump to source` link.

I think I got it it now that basically we get provided with `-1` or `0` in case of a `NULL` type.

**Comment by tim-weis** [comment]
> I think I got it it now that basically we get provided with `-1` or `0` in case of a `NULL` type.

The `windows-sys` crate doesn't provide this translation. It is ultimately a transliteration of the raw C API calls into Rust. There aren't any automatic conversions applied, and error handling is essentially the same as you would have implement it in C. If an API call is documented to return `NULL` in case of error, you would compare the `HANDLE` against `0`. If an API call is documented to return `INVALID_HANDLE_VALUE` on error you would instead compare the return value against `-1` or [`INVALID_HANDLE_VALUE`](https://docs.rs/windows-sys/latest/windows_sys/Win32/Foundation/constant.INVALID_HANDLE_VALUE.html).

The `windows` crate is different: It provides a custom [`HANDLE`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Foundation/struct.HANDLE.html) type with convenience functions (such as [`is_invalid`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Foundation/struct.HANDLE.html#method.is_invalid)). It is this `HANDLE` type that considers both `-1` and `0` invalid, because [`HANDLE` return values \[are\] so inconsistent](https://devblogs.microsoft.com/oldnewthing/20040302-00/?p=40443).

For a short description of the differences between `windows` and `windows-sys` see the FAQ entry [How do I choose between the `windows` and `windows-sys` crates?](https://github.com/microsoft/windows-rs/blob/master/docs/FAQ.md#how-do-i-choose-between-the-windows-and-windows-sys-crates).
