### ISSUE TITLE
Feature request: Add comments for the samples

### ISSUE THREAD

**Issue by MEisebitt** [microsoft/windows-rs#2140]
### Motivation

- Easier to understand especially for newcommers

### Drawbacks

- None really (except it takes time)

**Comment by Paul-Dempsey** [comment]
I might be willing to spend some time on this as an easy-start contribution. However, as the issue is written, it's not very actionable. What kind of commenting would be most useful (for you, or in general)? Are you looking for API usage information, Rust<->Windows mapping, or run-of-the-mill code commenting?

**Comment by kennykerr** [comment]
Feel free to contribute comments for individual samples if something's unclear. The challenge with commenting the samples in general is that it depends on what you know about Windows and Rust and your unique background and experience. 

I'm also working on a more complete guide to getting started that should help with explaining concepts:

https://kennykerr.ca/rust-getting-started/
