### ISSUE TITLE
windows-0.43.0: When use the match then find the constant values were the same, so I wondered whether this is a bug.

### ISSUE THREAD

**Issue by conero** [microsoft/windows-rs#2145]
when use `match` for NetworkAuthenticationType get `warning: unreachable pattern`, that I found the same value of `Wpa3Enterprise` and `Wpa3Enterprise192Bits` , so I wondered whether this is a bug.

```rust
// windows::Networking::Connectivity::NetworkAuthenticationType
let desc = match nss.NetworkAuthenticationType().expect("Failure") {     
      NetworkAuthenticationType::Wpa3Enterprise => "Wpa3Enterprise",
      NetworkAuthenticationType::Wpa3Enterprise192Bits => "Wpa3Enterprise192Bits",
      //...
      _ => "Unknown",
  };
```

![image](https://user-images.githubusercontent.com/19564821/200728904-ee1eca69-475e-4a62-8a8d-f8d5e0ebdf3d.png)

**Comment by kennykerr** [comment]
That's consistent with the metadata in the Windows SDK as well as the documentation:

https://learn.microsoft.com/en-us/uwp/api/windows.networking.connectivity.networkauthenticationtype?view=winrt-22621

For what it's worth, the documentation gives a rationale for the two identical constants. 

Incidentally, this is a good example for why Rust enums can't be used since it is an error for two variants to share the same discriminant, or value, in Rust. 

fyi @jonwis
