### ISSUE TITLE
windows_sys::Win32::Graphics::Direct2D contains APIs that need Foundation_Numerics

### ISSUE THREAD

**Issue by glandium** [microsoft/windows-rs#2185]
It contains the following functions:
- `D2D1ComputeMaximumScaleFactor`
- `D2D1InvertMatrix`
- `D2D1IsMatrixInvertible`
- `D2D1MakeRotateMatrix`
- `D2D1MakeSkewMatrix`

and types:
- `D2D1_BRUSH_PROPERTIES`
- `D2D1_DRAWING_STATE_DESCRIPTION`
- `D2D1_DRAWING_STATE_DESCRIPTION1`
- `D2D1_INK_STYLE_PROPERTIES`
- `D2D1_LAYER_PARAMETERS`
- `D2D1_LAYER_PARAMETERS1`

They are all behind the `Foundation_Numerics` feature, which doesn't exist, and the `Foundation::Numerics` types they rely on are not exposed in the crate.

**Comment by glandium** [comment]
There's something similar in `windows_sys::Win32::System::WinRt`, which has `CreateDispatcherQueueController` behind the non-existent `System` feature, using a `::System::DispatcherQueueController` type that doesn't exist in windows-sys.

**Comment by kennykerr** [comment]
Yep, there are a few such instances where the corresponding types in the `windows` crate are excluded from the `windows-sys` crate (notably all WinRT APIs) since the `windows-sys` crate lacks support for COM and WinRT. I've been meaning to exclude more of the COM-heavy namespaces from `windows-sys`, which should also help reduce the overall size and potential for breaking changes. 

https://github.com/microsoft/windows-rs/blob/773f19970b225668d4e314c35e5cc76d0220d6af/crates/tools/sys/src/main.rs#L6
