### ISSUE TITLE
Feature request: Use `c_char` pointer instead of `u8` pointer in string pointer types

### ISSUE THREAD

**Issue by icedrocket** [microsoft/windows-rs#2188]
### Motivation

In Rust, `c_char` poiner is generally used to pass a null-terminated string across C FFI boundry. Since `c_char` is defined as `i8` and not `u8`, it cannot be used directly in a function call that accepts a null-terminated string as a `u8` pointer. `i8` and `u8` are the same size, but are treated as completely different types.

windows-rs defined `PSTR` and `PCSTR` as a `u8` pointer, so we cannot directly use `CStr::as_ptr`. We should cast its return value to a `u8` pointer once before any call.

### Drawbacks

- When calling a function that accepts also a string length parameter, then `CStr` is not necessary.
- When there is a `u8` slice that is also valid C string, `CStr` is not necessary and we should cast `u8` pointer to `i8` pointer.

### Rationale and alternatives

- Modify APIs to pass `CStr` directly, and convert to pointer internally. I'm not sure this method is appropriate for the Win32 API.

**Comment by kennykerr** [comment]
Which crate are you using?

**Comment by icedrocket** [comment]
I'm using windows-sys 0.42.0. I wonder why you added the question label and removed the enhancement label.

**Comment by kennykerr** [comment]
Ignore the labels - that's just my way to manage and triage issues. 😊

The reason I ask is because the `windows` crate could conceivably provide parameter bindings to support `CStr` where `PCSTR` is expected, but the `windows-sys` crate cannot since it just provides raw bindings. 

While using `i8` might make it more convenient to use with `CStr` it would make it less convenient with `str` which uses `u8` so I'm not sure this is a good idea, ignoring any other compat issues that this may introduce. Still, feel free to bring it up on the metadata repo to see what those folks think. The underlying type is defined by the [Win32 metadata](https://github.com/microsoft/win32metadata/) project.

**Comment by icedrocket** [comment]
I think defining a new type would also be a good way.

```rust
pub trait Byte: Sized {}

impl Byte for i8 {}
impl Byte for u8 {}
```
