### ISSUE TITLE
Feature request: Easily convert PCWSTR/PWSTR into HSTRING

### ISSUE THREAD

**Issue by zhouhang95** [microsoft/windows-rs#2245]
### Motivation

Now way:
```
let foo: PCWSTR = w!("foo");
let bar = HSTRING::from_wide(foo.as_wide());
```
What I want:
```
let foo: PCWSTR = w!("foo");
let bar = foo.into();
```

**Comment by kennykerr** [comment]
I suspect that `let bar = foo.into();` would be ambiguous. You'd probably need `let bar: HSTRING = foo.into();` but that also wouldn't work since the conversion from `PCWSTR` would be unsafe so a `From` implementation could not be provided. `PCWSTR` does however provide an unsafe `to_string` method that produces a `String` that you could try. There's also the `h` macro that produces a const `HSTRING` directly.

**Comment by zhouhang95** [comment]
Could add method unsafe PCWSTR::to_hstring ?

**Comment by kennykerr** [comment]
And the motivation for `to_hstring` over and above `to_string` is so that you can produce an owned null-terminated wide string? Just making sure we're solving the right problem. 😉

**Comment by zhouhang95** [comment]
Yes,
Current way needs two functions.
Way 1:
```
let foo: PCWSTR = w!("foo");
let bar = HSTRING::from_wide(foo.as_wide());
```
or
Way 2:
```
let foo: String = w!("foo").into();
let bar: HSTRING = foo.into();
```
In way 2, UTF16->UTF8->UTF16, too strange.
When I first use windows-rs lib, I use way 2.
But I think way 1 is better and should in one function to do it.
