### ISSUE TITLE
LOWORD and HIWORD macro

### ISSUE THREAD

**Issue by bibhas2** [microsoft/windows-rs#2273]
### Motivation

The LOWORD and HIWORD macros are used heavily in win32. They appear to be missing in this crate.

### Drawbacks

Unable to write some win32 code without these macros.

### Rationale and alternatives

Shim used:

```rust
pub fn LOWORD(l: usize) -> usize {
    l & 0xffff
}

pub fn HIWORD(l: usize) -> usize {
    (l >> 16) & 0xffff
}
```

**Comment by kennykerr** [comment]
https://kennykerr.ca/rust-getting-started/where-are-the-macros.html

**Comment by kennykerr** [comment]
Macros are not included - here's a brief rationale - happy to expand on it if there's something missing: 

https://kennykerr.ca/rust-getting-started/where-are-the-macros.html

**Comment by bibhas2** [comment]
We see macros like ``s!()`` and ``w!()`` manually coded for this library. I don't see why other useful macros can not be added. If, however, you have decided not to add any more macros I understand.

**Comment by kennykerr** [comment]
It's certainly subjective. Note that `s!` and `w!` don't correspond to Windows SDK macros. There are thousands of macros in the Windows SDK headers. Rather than picking favorites, I'd rather keep the `windows` crate focused on code generation and allow other crates to develop with additional helpers.
