### ISSUE TITLE
Feature request: Make syn, quote and proc-macro2 optional when implementing COM interfaces.

### ISSUE THREAD

**Issue by hasenbanck** [microsoft/windows-rs#2289]
### Motivation

While porting the DirectStorage API to Rust we only used the interface proc macro as a starting point and the customized the expanded code to have more control of the generated API and provide a better user experience of the crate. This works in general fine, but the `IUnknown_Vtbl:::new()` function is behind the `interface` or `implement` feature, which pulls in some depdencies that the end user might now want to include (since they are not used by us).

It would be good to somehow enable external crates to implement COM objects without the need to pull in the proc macro dependencies.

**Comment by kennykerr** [comment]
Yes, this is something I'd love to fix.

**Comment by hasenbanck** [comment]
Thanks for the reply. A short ping once something is available for testing would be great! It's not time critical in any way.

**Comment by kennykerr** [comment]
> we only used the interface proc macro as a starting point and the customized the expanded code to have more control of the generated API and provide a better user experience of the crate.

I'm working on the eventual replacement for the `interface` macro and it would be helpful to know what's lacking that you chose to roll your own experience. Can you expand?

**Comment by hasenbanck** [comment]
Using the interface macro had the following problems for us:

1. It didn't work well with some IDEs like the InteliJ Rust plugin in our experience (traits and structures got mixed up).
2. You couldn't customize the public API signature. This was a problem, since we wanted to provide the same abstraction level as windows_rs itself:

```rust

// With the macro we had to expose this API:
pub unsafe fn CreateStatusArray(
    &self,
    capacity: u32,
    name: PCSTR,
    riid: *const GUID,
    ppv: *mut *mut c_void,
) -> HRESULT;

// But we wanted to have this API:
pub unsafe fn CreateStatusArray<T>(&self, capacity: u32, name: PCSTR) -> Result<T>
where
    T: Interface,
{...}
````

The argument that users might not want to pull in syn, quote and proc-macro2 for better build times still applies.

**Comment by kennykerr** [comment]
Just checking in with this older issue. I don't really see a practical solution for removing the `syn` dependency in particular nor a compelling reason to do so. Feel free to chime in if you disagree, otherwise I'll close this issue.

**Comment by MarijnS95** [comment]
(I'm subscribed to this issue even though I don't recall needing this, but chiming in anyway since it relates to what we found/discussed in https://github.com/microsoft/windows-rs/issues/2694#issuecomment-1795338013)

> This works in general fine, but the `IUnknown_Vtbl:::new()` function is behind the `interface` or `implement` feature, which pulls in some depdencies that the end user might now want to include (since they are not used by us).

Since the split to `windows-core` this is no longer the case. `windows-core` still has `IUnknown_Vtbl::new()` behind a feature flag:

https://github.com/microsoft/windows-rs/blob/1a2a9920df38678d1be4c6a6a6d43489a30ef4e9/crates/libs/core/src/unknown.rs#L86-L88

But (as per the comment linked above) is no longer also including the proc-macro crates, that only happens in the main `windows` crate:

https://github.com/microsoft/windows-rs/blob/1a2a9920df38678d1be4c6a6a6d43489a30ef4e9/crates/libs/windows/Cargo.toml#L30

---

That should solve your dependency question. It however seems (from that `IUnknown_Vtbl` implementation) that `trait` implementations still get raw pointers instead of high-level (including ownership transfer) types in the function signature.

**Comment by hasenbanck** [comment]
Hi!

I haven't been keeping track with the changes that happened between 0.42 and 0.51, so I can't comment about changes on the old requirements right now.

I have also delayed the update of the direct storage crate to wait until the development in the upstream project stablized and it seems now a good point to pull the changes from the current 1.2.1 version.

I just realized that they now provide a "Microsoft.Direct3D.DirectStorage.winmd" metadata file, so most likely I shouldn't write the bindings manually anymore and should automatically generate them now.

**Comment by MarijnS95** [comment]
> I just realized that they now provide a "Microsoft.Direct3D.DirectStorage.winmd" metadata file, so most likely I shouldn't write the bindings manually anymore and should automatically generate them now.

Definitely, that makes _total_ sense with the `windows-core` crate. In case you need a minimal example, see:

https://github.com/Traverse-Research/amd-ext-d3d-rs

In short you have to create a `bindings.txt` that configures how to generate rust code and call the generator on it. `riddle` isn't yet published so that you can do `cargo install riddle; riddle --etc bindings.txt`, so there's the `api_gen` crate that depends on the _published_ `windows-bindgen` crate via `windows_bindgen::bindgen(["--etc", "bindings.txt"])` instead.

Hope that helps!

**Comment by MarijnS95** [comment]
> I have also delayed the update of the direct storage crate

On a somewhat related note, there appear to be 3 of these crates, 2 of which are from @damyanp/@kennykerr and have been yanked, but crates.io shows those two at the top :sweat_smile:
