### ISSUE TITLE
Feature request: Get access to remaining refcount from `.Release()`

### ISSUE THREAD

**Issue by MarijnS95** [microsoft/windows-rs#2291]
### Motivation

In certain APIs, such as [when freeing placed `ID3D12Resource`s](https://github.com/Traverse-Research/gpu-allocator/pull/151#discussion_r1071304115) prior to clearing up the underlying allocation it would be beneficial to assert that `.Release()` returns `0`; i.e. we are the last owner of this object.

I typed up a test locally to validate refcounts:

```rust
impl IUnknown {
    /// Returns the remaining refcount after dropping the object
    #[must_use = "Use regular Drop semantics if the remaining refcount is not needed"]
    pub fn release(self) -> u32 {
        let intf = std::mem::ManuallyDrop::new(self);
        unsafe { (intf.vtable().Release)(std::mem::transmute_copy(&intf)) }
    }
}
```

And use it like:

```rust
let r = ManuallyDrop::into_inner(resource.resource);
assert_eq!(IUnknown::from(r).release(), 0);
```

### Drawbacks

Extra complexity/code to maintain?

### Rationale and alternatives

The only alternative is not checking this refcount and assuming that the COM object disappears when we drop it (because we're *supposed to be* the last owner).

### Additional context

This is similar to using `Arc::try_unwrap().unwrap()` to make sure that an `Arc` isn't kept alive elsewhere, when in a shutdown path (i.e. we've used it to detect cyclic dependencies in the past).

#### Bonus

I doubt anyone needs access to the clone refcount, but we could similarly provide it:

```rust
    pub fn add_ref(&self) -> (Self, u32) {
        let c = unsafe { (self.vtable().AddRef)(std::mem::transmute_copy(self)) };

        (Self(self.0), c)
    }
```

(And implement `fn clone` in terms of `self.add_ref().0`)

**Comment by MarijnS95** [comment]
@kennykerr ack, this is a debug purpose (and should probably switch to `debug_assert!` to that effect) and it depends on the kind of object whether it meaningfully implements these.

I've seen cases where `1` is returned, but that's for singletons that are always alive statically and can never be dropped. `ID3D12Resource` seems to implement something proper, but if you're confident that that's just appearance, we'll have to live dangerously here :/

**Comment by damyanp** [comment]
Note that D3D12 isn't a COM API - it uses IUnknown, but doesn't use any of the COM runtime - and so doesn't interact with CoUninitialize.

When working with placed d3d12 resources, where one or more ID3D12Resources are "placed" into a ID3D12Heap, the application needs to implement some kind of allocation scheme for the resources in this heap.  I think that @MarijnS95 is looking for a way to verify that when they tell their allocator that a resource has been destroyed that it really has been destroyed.  

Release() returning 0 then that's traditionally been a pretty good indicator that the object has been destroyed - and that if for some reason Release() hasn't returned zero at this point then they'll need to track down what other thing is keeping that object alive.  I don't think that there's any meaningful values other than zero or non-zero here.

D3D12 is pretty unique in that there's an entire set of object lifespans going on involving things running on the GPU.  For example, an ID3D12GraphicsCommandList can be used to write commands to a ID3D12CommandAllocator.  If the GPU is asked to execute the command list, then that command allocator must not be destroyed until after the command list has finished executing.  ID2D12Fence objects are used to determine when this has happened.  It is up to the developer to keep track of all of this, and I think that may well result in cases where it's useful to be able to assert that a Release() call did or did not result in destroying the object.  

Possibly though, since this only really applies to one set of APIs (it doesn't apply to D3D11 for example), I'm not sure this belongs in windows-rs proper.  It should be possible to implement a "last_drop" or "not_last_drop" function in application code I think?

**Comment by kennykerr** [comment]
I could add a `release` helper for this purpose. The trouble I've historically had with such helpers is that they tend to confuse developers into thinking that they _should_ call it in all cases "just in case" lest things don't get released properly. It's the same reason I don't provide handy wrappers for things like `CoInitializeEx` and `CoUninitialize`. But you're certainly welcome to write your own helper that exposes the ref count for the rare case where it matters.

**Comment by MarijnS95** [comment]
> I could add a `release` helper for this purpose. [..] But you're certainly welcome to write your own helper that exposes the ref count for the rare case where it matters.

And contribute that helper to this repo? I can definitely PR the suggestion above, and opened this issue mostly for feedback and improvements before doing so :)

> The trouble I've historically had with such helpers is that they tend to confuse developers into thinking that they _should_ call it in all cases "just in case" lest things don't get released properly. It's the same reason I don't provide handy wrappers for things like `CoInitializeEx` and `CoUninitialize`.

Agreed, hence my suggestion above explicitly includes `#[must_use]`, explaining that if the refcount is not needed regular drop semantics should be used (and we could bikeshed the wording/linking to make sure this is understood). If developers refuse to understand that... well... maybe `drop` semantics aren't explained properly (neither on the Rust side, nor that windows-rs implements them correctly)?

For now it is anyway only available on `IUnknown` and hidden behind an `IUnknown::from()`, any suggestions about that or is that instead a good barrier?

**Comment by riverar** [comment]
> And contribute that helper to this repo? I can definitely PR the suggestion above, and opened this issue mostly for feedback and improvements before doing so :)

No, don't think we want that here. I don't see it as being particularly valuable--traditional and reliable COM teardown happens already at process termination. It not clear what developers should/can do if `Release` returned non-zero.

**Comment by kennykerr** [comment]
Yes, I wasn't suggesting adding to `windows-rs` - it's definitely an anti-pattern so I wouldn't want to promote it here.
