### ISSUE TITLE
Is there a way to use share ISWbemLocator between threads?

### ISSUE THREAD

**Issue by cemremengu** [microsoft/windows-rs#2336]
Sorry if this does not make sense since I am a bit to Rust and windows API in general:

I am trying to create an async web service which will accept WMI queries together with connection info and return the results.

However, the queries (`ISWbemLocator` I think) look like it is blocking when I send multiple requests even if I use something like `tokio::task::spawn_blocking`

I tried to `ISWbemLocator` between threads in order so that each request can crate its own connection to solve this but (as expected) I am getting `std::ptr::NonNull<std::ffi::c_void> cannot be shared between threads safely`.

Is there a way to achieve this at the moment (or ever) ? If there is another way could you please provide some hints?

**Comment by kennykerr** [comment]
The issue is that the interface is not known to be thread-safe so the `windows` crate doesn't provide the [Send and Sync traits](https://doc.rust-lang.org/stable/std/marker/trait.Sync.html) that indicate this to the compiler. Recall that the `windows` crate [is generated from metadata](https://kennykerr.ca/rust-getting-started/how-are-crates-built.html) so the metadata would need to indicate this before the `windows` crate could reliably generate these traits.

If you know a given API is thread-safe (and agile), you can simply wrap them in a struct that does implement `Send` and `Sync` and off you go.
