### ISSUE TITLE
delay_load: FreeLibrary possible called too eagerly

### ISSUE THREAD

**Issue by AronParker** [microsoft/windows-rs#2354]
https://github.com/microsoft/windows-rs/blob/1f8e1dd64bb31c286c683506834811b281b6d396/crates/libs/windows/src/imp/delay_load.rs#L10-L25

The `FreeLibrary` call here is possibly too eagerly called. LoadLibrary increments a reference count, FreeLibrary decrements the reference count. When the reference count reaches zero, [the module is unloaded](https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-freelibrary). `GetProcAddress` does not interact with the reference count, therefore a procedure address to a potentially unloaded library would be acquired.

The `delay_load` code only works when the module has been previously loaded with a nonzero reference count. Ideally delay_load would be more sophisticated and return a RAII based object that calls FreeLibrary should the function pointer no longer be used.

**Comment by ChrisDenton** [comment]
Hm. surely this only calls `FreeLibrary` on failure (i.e. there is no function address)? Though I guess it could be written to make this more clear. I.e. this is roughly:

```rust
    let library = LoadLibraryA(library);         // +1 ref count
    if library == 0 { return None; }
    let address = GetProcAddress(library, function);
    if address.is_null() { 
        FreeLibrary(library);                    // -1 ref count
        None                                     // no address is returned
    } else {
        Some(std::mem::transmute_copy(&address)) // leak library
    }
```

**Comment by AronParker** [comment]
Ah, in my tunnelvision I failed I see that I'm sorry. Though I always wondered why it is commonpractice to leak the library like this, but I suppose if you use the function forever that is perfectly acceptable. Again sorry for my negligence, I'll re-read it more carefully next time!

**Comment by ChrisDenton** [comment]
Better safe than sorry! I think it's a good idea to ask even if you risk having missed something.

As for library leaking, this is usually best practice in a general purpose function such as this because library unloading can be incredibly unsafe whereas it's always safe to leak the DLL. Even with RAII it's very hard to know if some thread somewhere is still using a resource (even if indirectly) that the DLL unload will free. So unless you know about the specific DLL and how it's being used, it's better to leak. Well, even if you do know then it's still *safer* to leak unless you really need to reclaim the memory or something.
