### ISSUE TITLE
Bug: LocalFree returns Error(code=ERROR_SUCCESS) instead of success

### ISSUE THREAD

**Issue by mtth-bfft** [microsoft/windows-rs#2392]
### Which crate is this about?

windows

### Crate version

0.46.0

### Summary

`LocalFree` (which is legacy, but still required by non-legacy functions) and potentially other functions with the same prototype return a `windows::core::Result<>` which may be a `windows::core::Error`. In success cases, the result is an `Error` containing a code 0 (`ERROR_SUCCESS`) instead of a success, which adds convoluted code to check twice for nested error cases, and makes it impossible to simply unwrap() or use the `?` operator or any of the idiomatic Rust ways of handling `Error`s.

### Toolchain version/configuration

Default host: x86_64-pc-windows-msvc

installed toolchains
--------------------

stable-i686-pc-windows-msvc
stable-x86_64-pc-windows-msvc (default)

installed targets for active toolchain
--------------------------------------

i686-pc-windows-msvc
x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.67.0 (fc594f156 2023-01-24)

### Reproducible example

```rust
let sid = PCSTR("S-1-5-18\0".as_ptr());
let mut p_sid = PSID(null_mut());
let succeeded = unsafe { ConvertStringSidToSidA(sid, &mut p_sid) };
if !succeeded.as_bool() {
    todo!();
}
// Do something with psid
unsafe { LocalFree(HLOCAL(psid.0 as isize)).unwrap(); } // panics
```

### Expected behavior

`LocalFree` should return `Ok` in case of success

### Actual behavior

`LocalFree()` returns an `Error` which contains a `HRESULT` which `is_ok`:

```rust
let res = unsafe { LocalFree(HLOCAL(psid.0 as isize)) };
if let Err(e) = res {
    if e.code().is_err() {
        // Do something with e
    }
}
```

**Comment by kennykerr** [comment]
`LocalFree` is an odd duck since it reports success by returning an invalid handle. Conversely, it reports failure by returning a valid handle, its input. This confuses the `Result` and makes it of little use. On the other hand, the only reason `LocalFree` would fail is if you passed an invalid handle, so checking the result isn't particularly useful. I typically just call it as follows:

```rust
_ = LocalFree(buffer);
```

Unfortunately, this is just the way the function is designed and I'm not sure there's an obvious solution beyond the suggestion above.

**Comment by tim-weis** [comment]
Agreed, if the call to `LocalFree` fails, your program is already in trouble due to a previous error, and *that* error needs to be fixed. Though even if the issue is discovered late, it's still better to terminate the process in a timely fashion, and I like to at least `debug_assert!` here.

Luckily, this doesn't require checking twice. The following will do just fine (making use of the [`OK`](https://microsoft.github.io/windows-docs-rs/doc/windows/core/struct.Error.html#associatedconstant.OK) constant):

```rust
let res = LocalFree(hloc);
debug_assert_eq!(res, Err(windows::core::Error::OK), "LocalFree() failed");
```

Keep in mind that, depending on exactly how wrong the `HLOCAL` input is, the behavior could be either one of the following:

* `LocalFree()` reporting failure, with a subsequent call to `GetLastError()` returning an error code such as `ERROR_INVALID_HANDLE`, or `ERROR_NOACCESS`
* `LocalFree()` reporting success, even though it corrupted a region of memory that just happened to look valid enough
* `LocalFree()` internally shutting down the process with a `STATUS_HEAP_CORRUPTION` exit code
