### ISSUE TITLE
Some releases are missing in crates.io

### ISSUE THREAD

**Issue by saschanaz** [microsoft/windows-rs#2469]
https://crates.io/crates/windows/versions

Notably 0.45.0, 0.47.0 and 0.49.0, Is there a rule for this? 👀

**Comment by kennykerr** [comment]
Releases are documented here: 

https://github.com/microsoft/windows-rs/releases

As you can see, not every crate is updated with every release but each release increments the version number. I do this so that we can have a simple way to tag releases on GitHub:

https://github.com/microsoft/windows-rs/tags

This is convenient for the time being, but I suspect it I will have to change once the crates are stable (1.0).

**Comment by saschanaz** [comment]
Got it, thanks!
