### ISSUE TITLE
Feature request: Add macro wrapper to Result<> for win32 fn calls

### ISSUE THREAD

**Issue by mapasco-msft** [microsoft/windows-rs#2490]
### Motivation

I often find myself writing code like: 
![image](https://user-images.githubusercontent.com/52797173/236301020-3cf835bc-a376-4933-9b2d-f9a1e8b03883.png)

Propose to include a wrapper that will return a `Result<win 32 response, Your provided error>`

This can be achieved such as:

![image](https://user-images.githubusercontent.com/52797173/236301266-312f412c-c8f5-4f36-b175-c0e63db8cb11.png)
![image](https://user-images.githubusercontent.com/52797173/236301376-67d7913a-dd86-4657-b5ca-f3f85b72874c.png)

### Drawbacks

These macros may not handle all return types. This also expects 0 or null to be the error case. An additional macro argument could be passed for expected error result 

### Rationale and alternatives

I continually find myself to write this win32 result error checking and adds extra lines of code

**Comment by kennykerr** [comment]
I assume you're referring to the `windows-sys` crate since the `windows` crate already provides the more idiomatic bindings such that the `GetFileVersionInfoExW` function returns `Result<()>` so there's no need for a macro. It handles this scenario reliably. Two thoughts:

* Use the `windows` crate. 😊
* It's tempting to add bells and whistles, but the goal is to keep these crates as minimalist as possible. Various helpers can be added atop using distinct crates.

**Comment by mapasco-msft** [comment]
correct, if I recall there was some limitations to using just the `windows` crate for my scenario. I might reevaluate that need

**Comment by riverar** [comment]
Do ping us here (or Kenny behind the scenes) with your blockers, it's great data to have and could drive fixes/improvements. Thanks!
