### ISSUE TITLE
Bug: `DefWindowProcW` can not be used in `WNDCLASSEXW` directly

### ISSUE THREAD

**Issue by lostmsu** [microsoft/windows-rs#2556]
### Which crate is this about?

windows

### Crate version

0.48

### Summary

```rust
let window_classx = WNDCLASSEXW {
  lpfnWndProc: Some(DefWindowProcW),
  ..Default::default()
};
```

fails to compile due to incompatibility between `WNDPROC` used for `lpfnWndProc` and `DefWindowProcW`

### Toolchain version/configuration

Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\REDACTED\\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc (default)
nightly-x86_64-pc-windows-msvc

active toolchain
----------------

nightly-x86_64-pc-windows-msvc (directory override for 'C:\Users\REDACTED\Projects\retour-rs')
rustc 1.72.0-nightly (36fb58e43 2023-06-26)

### Reproducible example

```rust
use windows::Win32::UI::WindowsAndMessaging::*;

let window_classx = WNDCLASSEXW {
  lpfnWndProc: Some(DefWindowProcW),
  ..Default::default()
};
```

### Expected behavior

The above should compile

### Actual behavior
```
|         lpfnWndProc: Some(DefWindowProcW),
|                           ^^^^^^^^^^^^^^ expected "system" fn, found "Rust" fn
|
= note: expected fn pointer `unsafe extern "system" fn(HWND, _, WPARAM, LPARAM) -> LRESULT`
                  found fn item `unsafe fn(_, _, _, _) -> LRESULT {DefWindowProcW::<'_, _, _, _>}`
```

**Comment by kennykerr** [comment]
That's not a complete repro but I think I see what you're trying to ask. 😉

The system-provided `DefWindowProcW` function is not a callback, so it can't be passed in the place of a callback (as you would in C or C++) using the `windows` crate since it is not a function pointer. If you need that to compile, I suggest you do one of:

* use the `windows-sys` crate where this will work as is since functions aren't wrapped
* declare `DefWindowProcW` yourself using the `windows-targets` crate
* call `DefWindowProcW` from your own window procedure using the `windows` crate

The last option is probably simplest if you're already using the `windows` crate.

**Comment by riverar** [comment]
We also have a sample that covers CreateWindow basics https://github.com/microsoft/windows-rs/blob/master/crates/samples/windows/create_window/src/main.rs
