### ISSUE TITLE
One-tuple structs should implement `Deref` and `DerefMut`

### ISSUE THREAD

**Issue by Enyium** [microsoft/windows-rs#2732]
### Suggestion

This would spare us of the ugly and unpleasant `.0`, giving us nice `*` dereffing. The relationship from the outer to the inner type can be seen as similar to `Vec<u8>` to `&[u8]` or `String` to `&str`.

This would be especially useful for types like `WPARAM` and `LPARAM` that the developer must numerically crunch on their own. But I also already came across cases where I had to switch the handle type like so:

```
pub fn duplicate_hicon(hicon: HICON) -> Result<HICON, windows::core::Error> {
    unsafe { CopyImage(HANDLE(hicon.0), IMAGE_ICON, 0, 0, IMAGE_FLAGS(0)) }
        .map(|handle| HICON(handle.0))
}
```

**Comment by riverar** [comment]
Note the documentation for `Deref` states these traits should only be used in smart pointer scenarios (https://doc.rust-lang.org/std/ops/trait.Deref.html).

The `CopyImage` API is awkward in that it accepts `HICON`, `HCURSOR`, and `HBITMAP` opaque handle types, but rather than create multiple APIs or parameters, it represents all those inputs with an incompatible `HANDLE` type.

This is common in Win32 and the upstream metadata project has an attribute that can be used to express this ([`AlsoUsableFor`](https://github.com/microsoft/win32metadata/blob/main/docs/projections.md?plain=1)). The windows crate generates the appropriate `CanInto` trait implementations when it detects the attribute.

https://github.com/microsoft/windows-rs/blob/8e71051ea8a57594478e585d2740126893f9dbb7/crates/libs/bindgen/src/rust/handles.rs#L92-L105

So let's create an issue in https://github.com/microsoft/win32metadata to get this function annotated as such.

**Comment by Enyium** [comment]
> Note the documentation for Deref states this trait should only be used in smart pointer scenarios

Oh, you're right. They make that quite clear. Looks like no improvement possible on the `.0` front.

But I indeed wondered why there are no conversions defined for the handle types. Although, `impl From<HANDLE> for HICON` seems a bit off. Reminds me of different cast directions in C# for classes with one being potentially unsafe.

**Comment by kennykerr** [comment]
> Note the documentation for Deref states this trait should only be used in smart pointer scenarios 

Closing as per the docs.
