### ISSUE TITLE
`ok()` function for handle types

### ISSUE THREAD

**Issue by Enyium** [microsoft/windows-rs#2736]
### Suggestion

To better harmonize with `Result`-oriented surrounding code, handle types like [`HANDLE`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Foundation/struct.HANDLE.html#), [`HBRUSH`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Graphics/Gdi/struct.HBRUSH.html#), [`HBITMAP`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Graphics/Gdi/struct.HBITMAP.html#), [`HRGN`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Graphics/Gdi/struct.HRGN.html#), [`HWND`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Foundation/struct.HWND.html#) etc. should have an `ok()` function similar to that of [`BOOL`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Foundation/struct.BOOL.html#) to yield the value wrapped in `Ok` or an `Err` with `windows::core::Error::from_win32()`.

It could then be used for <https://github.com/microsoft/win32metadata/issues/1758>, or, if this issue won't be fulfilled, it would be even more vital to be able to do this on your own without too much trouble.

**Comment by tim-weis** [comment]
[Here be dragons](https://github.com/microsoft/windows-rs/issues/2734#issuecomment-1849885745). The contract for error reporting is a property of the API call. It cannot be implemented in a type that's used across API calls with different error reporting contracts.

Take `HBITMAP` as an example. The vast majority of GDI functions that return `HBITMAP`s do not set the calling thread's last error code. As such there's no one correct way to do the `Result` transformation. The few cases where there is additional error information (e.g., [`CreateDIBSection`](https://learn.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-createdibsection)) already receive the appropriate treatment ([`CreateDIBSection`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Graphics/Gdi/fn.CreateDIBSection.html)).

In essence:

* Error reporting contracts cannot be attributed to types.
* If there is a single, loss-less `Result` transformation for a given API, the `windows` crate provides that transformation already.
* For everything else the only tractable solution is to delegate error discovery and propagation to clients.

**Comment by Enyium** [comment]
When you pointed out [here](https://github.com/microsoft/win32metadata/issues/1758#issuecomment-1851530106) that a number of functions don't make an error code available, I understood that this makes this issue shaky. But it still seems to me that basic means to write DRYer code should be provided by the `windows` crate. Maybe some handle returning function can never fail; but the handle type still has its `is_invalid()` method. Why can't it have a set of tools used under different circumstances? E.g., two functions that transform it into a `Result`, but only one of them calls `GetLastError()`, while the other one simly transforms an invalid handle into an `E_HANDLE` error.

A problem in this context may also be the unexpressiveness of `ok()`. It doesn't convey whether `GetLastError()` is called or just a simple check is performed and nothing more. I'm trying to fight against these imperfections of the `windows` crate with helper methods like [these](https://docs.rs/windows-helpers/latest/windows_helpers/error/trait.ResultExt.html) that make the code DRYer and more streamlined in `Result`-oriented surroundings.

From my perspective, the `windows` crate already accommodates the user to some extent. Many functions that in v0.48 still returned a `BOOL` not return a `Result`, and some functions like you pointed out return a `Result` for a fallible function where the return type isn't associated with `BOOL`. But it's all quite inconsistent, and I'm hoping for more accommodation and consistency.

**Comment by tim-weis** [comment]
> Why can't it have a set of tools used under different circumstances?

Because the code is [generated from metadata](https://kennykerr.ca/rust-getting-started/how-are-crates-built.html), and there isn't a whole lot of information available beyond (absence of) the `SetLastError = true` attribute. If you'd like to see the `windows` crate in a position to generate stricter code you'd have to introduce that information at the top of the pipeline (the [`win32metadata`](https://github.com/microsoft/win32metadata) repo).

That is challenging, and I doubt the metadata will ever encode the full set of API contracts (or that it should, for that matter). I still believe there is room for improvement, specifically around capturing [SAL annotations](https://learn.microsoft.com/en-us/cpp/c-runtime-library/sal-annotations) (apologies to @riverar, I said the "S-word" 😉 ).

Taking the example from above, `CreateDIBSection` (in *wingdi.h*) has this annotation: `_Success_(return != NULL)`. That could conceivably be included in the metadata to drive better code generation, on a per-API basis. There are **lots** of SAL annotations, and I'd like to see more of them making their way into the metadata, although I understand that the win32metadata team isn't thrilled about this idea.

> But it's all quite inconsistent

Such is the nature of an API that has been around for decades. The `windows` crate cannot fix history, and smoothing out the sharp edges should be delegated to dedicated crates.

**Comment by kennykerr** [comment]
This:

> Such is the nature of an API that has been around for decades. The windows crate cannot fix history, and smoothing out the sharp edges should be delegated to dedicated crates.
