### ISSUE TITLE
Opening this crate in vscode on Linux leads to files being changed and an endless build loop

### ISSUE THREAD

**Issue by RalfJung** [microsoft/windows-rs#2777]
### Summary

To reproduce, download this crate and open it in vscode on Linux with rust-analyzer installed. (I did that since I needed to grep for some things the crate does to research Windows-related issues in my code, and I don't have a Windows machine.) This leads to changes showing up in `git diff`, and rust-analyzer hangs in an endless build loop. I reported this with RA at https://github.com/rust-lang/rust-analyzer/issues/16250 but they are saying there isn't much they can do; the reason is that this crate modifies its own source in a build script which causes a reload which causes a build which modifies the source again ad nauseam.

**Comment by kennykerr** [comment]
I don't use rust-analyzer because it makes VS Code unusable with the windows-rs repo. I don't really know what to do about that. It seems more of a rust-analyzer issue to me but perhaps I'm biased. The repo is just very _very_ large and contains not only the `windows` and `windows-sys` crates in their entirety but also contains all of the code generation tooling, the `windows-bindgen` crate, that produces those crates. That tooling has very extensive testing included in the windows-rs repo that necessarily uses build scripts to generate a lot of code. While unusual, I don't see this as a bug. 

Adding @ChrisDenton and @riverar perhaps they have more perspective.

**Comment by ChrisDenton** [comment]
A workaround might be to exclude `crates/tests/*` from the workspace on your local copy, or maybe just exclude it from ra.

 Maybe ra

**Comment by ChrisDenton** [comment]
Btw, I don't think doing codegen in build scripts is too bizarre. While it's rarer then other codegen methods (e.g. macros) it's not exactly unheard of.

**Comment by RalfJung** [comment]
Yeah codegen in build.rs is not uncommon and I think RA usually handles it fine. Not sure why it is causing a problem with this crate.

It does seem like build.rs is changing files in the `src` folder though, that is not common at all.  Usually it puts its output into the OUT_DIR and then they get included into the regular build.

**Comment by kennykerr** [comment]
That's so I can use git diff during github builds to verify nothing has changed.
