### ISSUE TITLE
ID3D11Device functions: `Result<T>` instead of using `Option<*mut Option<T>>` if possible?

### ISSUE THREAD

**Issue by Zerowalker** [microsoft/windows-rs#2795]
### Suggestion

There are many functions in `ID3D11Device` that uses `Option<*mut Option<T>>` which makes the code look something like this:

```rust
unsafe fn get_sampler_state(device: &ID3D11Device, desc: &D3D11_SAMPLER_DESC) -> windows::core::Result<ID3D11SamplerState> {
  let mut o = None;
  device.CreateSamplerState(desc,Some(&mut o))?;
  Ok(o.unwrap())
}
```

From what I can gather the `Option<T>` is always `Some` when the functions are `Ok` (perhaps some exceptions).
In that case is it possible to do like other winapi functions has been made and just return the object with the `Result`?

I don't really get why it expects `Option<*mut Option<T>>` and not just `*mut Option<T>` though,
but I'm probably missing something.

**Comment by kennykerr** [comment]
Here's the metadata representation for this particular API:

```C#
unsafe HRESULT CreateSamplerState([In][Const] D3D11_SAMPLER_DESC* pSamplerDesc, [Optional][Out][ComOutPtr] ID3D11SamplerState* ppSamplerState);
```

Notice the optional attribute on the trailing parameter. 

While such trailing COM output parameters would normally be transformed into a `Result<T>` return value, many of those cases in DirectX are intentionally optional parameters so that the caller can pass a null pointer to the API. This is often used as a way to test whether a given resource can be created before actually creating it. Unfortunately, this is just the way DirectX is designed and there isn't really anything we can do about it here.

**Comment by Zerowalker** [comment]
Ah, make sense, didn't think it was optional but I see that the documentation shows it as such, even though it doesn't explain why.
But in that case it makes sense, to pass null you give it None, but as one Option can't represent that you you have to have 2.
As `&mut Option<T>` can not determine if you passing a `&mut None` meant "null" or if you want it to be filled.

So even though it's a bit "weird" I can't really see how to otherwise represent it, so I see that it's very logical now that you explained it.

Was clearly a lack of looking up what was expected on my part, sorry for that.

Thanks for the explanation and quick response:)
