### ISSUE TITLE
`windows::Win32::System::Memory::GlobalUnlock` returns `Err` on success

### ISSUE THREAD

**Issue by wuweiran** [microsoft/windows-rs#2997]
### Summary

This function is tricky. According to the [doc](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-globalunlock), whether it is successful depends on the last error, not only on the boolean value returned.

**Comment by kennykerr** [comment]
The version of this function provided by the `windows` crate will capture the error code from `GetLastError` and store it in the `Error` value held by the `Err` variant. You can then inspect this value and decide what to do.

**Comment by wuweiran** [comment]
That isn't semantically correct. An API should not return an error and let the user figure out whether it failed or not.

I understand "windows-rs" wants to remain clean, with a simple mapping of `BOOL`=>`Ok`/`Err`, `Err` => `GetLastError`. And Windows API won't admit it has a bad API design. But I don't think it should always be the user who do the dirty work.

**Comment by kennykerr** [comment]
If you think this function would be better served without the error transformation, it would need to be attributed with something like `CanReturnMultipleSuccessValues`. 

You can certainly suggest that over at the Win32 metadata repo. https://github.com/microsoft/win32metadata

**Comment by riverar** [comment]
@wuweiran Are you using an API that requires you to call `GlobalUnlock`? Just curious.

**Comment by wuweiran** [comment]
@riverar I'm playing around with some personal stuffs where I want to call `SetClipboardData`. I read from some other project's code that I should `GlobalAlloc` a memory to set the clipboard data.

**Comment by Nordgaren** [comment]
> If you think this function would be better served without the error transformation, it would need to be attributed with something like `CanReturnMultipleSuccessValues`.
> 
> You can certainly suggest that over at the Win32 metadata repo. https://github.com/microsoft/win32metadata

I just wanted to clarify, because I ran into the same problem as OP. Would this be a suggestion to change the Windows API as a whole? Or is this just how you deal with the API tools for each different language package?

I am just curious, because I was wondering why not make a change to the Rust crate that won't interfere with the Windows API, but makes sense for Rust? Is it not possible to change the return type from `Result<()>` to `Result<LockStatus>`  with the `LockStatus` type looking like

```rust
pub enum LockStatus {
        Unlocked,
        Locked,
}
```

I don't know what the best way to transform the error from `BOOL::ok()`, but, it would be nice if the function returned an `Err(E)` only if there is actually an error. This would still communicate the status of the lock to the user, and they can use or ignore this value, as they are currently.

Maybe this isn't the greatest suggestion, which is why I am putting it second, but, maybe this can be worked with
```rust
    #[inline]
    pub fn ok(self) -> windows_core::Result<()> {
        if self.as_bool() {
            Ok(())
        } else {
            Err(windows_core::Error::from_win32())
        }
    }
```
To become this
```rust
    #[inline]
    pub fn ok(self) -> windows_core::Result<bool> {
        if self.as_bool() {
            Ok(true)
        } else {
            windows_core::Error::from_win32()
        }
    }
```

where `windows_core::Error::from_win32()` can return `Ok(false)` if it's `NO_ERROR`. or maybe there is a good way to return that enum from here and make it generic enough that it can be used in all placed you need to use `windows_core::Error::from_win32()`. Or maybe a specific method. IDK. I just ran into the same issue when helping a friend get Rust working for a new project, and, it is kind of confusing when an API function is succeeding, but still causing the program to die. `Err(NO_ERROR)` 🤔

**Comment by kennykerr** [comment]
https://kennykerr.ca/rust-getting-started/how-are-crates-built.html
