### ISSUE TITLE
Direct3D debug layer not showing in debug console

### ISSUE THREAD

**Issue by billgan1024** [microsoft/windows-rs#3031]
### Summary

Direct3D debug layer is not showing in debug console when LLDB debugging is used.

**Comment by riverar** [comment]
@billgan1024 Please complete the bug report. Closing for now but I'll check back later to see if you've provided more information.

**Comment by damyanp** [comment]
The D3D debug layer uses OutputDebugString to emit debugging messages. However, LLDB does not support the Windows debug output, which is why it doesn't show up.  Other debuggers do (eg the VS debugger). An interesting project might be to build use something like https://devblogs.microsoft.com/directx/d3d12-debug-layer-message-callback/ to connect this to Rust's debug output, but I think this is out of scope for windows-rs.
