### ISSUE TITLE
GetFileVersionInfoSizeW should return Result

### ISSUE THREAD

**Issue by sevenc-nanashi** [microsoft/windows-rs#3088]
### Suggestion

This function might fail according to the documentation:

> If the function fails, the return value is zero. To get extended error information, call [GetLastError](https://learn.microsoft.com/en-us/windows/desktop/api/errhandlingapi/nf-errhandlingapi-getlasterror).
> https://learn.microsoft.com/en-us/windows/win32/api/winver/nf-winver-getfileversioninfosizew

It should return `Result<u32>`.

**Comment by riverar** [comment]
I think you meant to quote this 🙂

> If the function succeeds, the return value is the size, in bytes, of the file's version information.

**Comment by riverar** [comment]
Looks like this was already fixed upstream (https://github.com/microsoft/win32metadata/commit/424d1fe948e401471886052bed798a50785312da); [we haven't brought in the latest metadata yet](https://github.com/microsoft/windows-rs/blob/master/crates/libs/bindgen/default/readme.md) due to some unrelated issues, but we'll get it in as soon as possible.
