### ISSUE TITLE
`TranslateMessage` falsely gives error

### ISSUE THREAD

**Issue by JunkuiZhang** [microsoft/windows-rs#3145]
### Summary

The code `TranslateMessage(&msg).ok()` will give `Err()`, which is wrong.

**Comment by JunkuiZhang** [comment]
![Screenshot 2024-07-04 160412](https://github.com/microsoft/windows-rs/assets/14981363/f18817b5-ebaf-4988-9f77-62c007de9436)

The error message is `"Operation successful"`;

**Comment by tim-weis** [comment]
> The code `TranslateMessage(&msg).ok()` will give `Err()`, which is wrong.

No, that is correct. The return value of [`TranslateMessage`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-translatemessage) indicates whether the API processed the message. It is not a success/error discriminator. The issue is converting the `BOOL` to a `Result<T>` via `ok()`.

The conventional use pattern for this API is to check whether the message was processed and pass it on to `DispatchMessageW()` if not, something like this:

```rust
if !TranslateMessage(&msg).as_bool() {
    DispatchMessageW(&msg);
}
```

**Comment by riverar** [comment]
Thanks Tim, beat me by a few seconds!

> By the way, I noticed some chages from `isize` to `*mut cvoid`, for example, `HWND`, `HANDLE`, `HMONOTOR`, `HMODULE`. And this change makes them thread unsafe, I have to manually `unsafe impl Sync Send ...` for them. Is this intended?

This was a recent change (https://github.com/microsoft/windows-rs/pull/3111). This now matches the Rust standard handle type [`std::os::windows::raw::HANDLE`](https://doc.rust-lang.org/std/os/windows/raw/type.HANDLE.html).

**Comment by riverar** [comment]
I do wonder if there's any value in having an `.ok()` impl for `BOOL`, given it unexpectedly calls GetLastError which could contain anything and confuse folks further.

**Comment by JunkuiZhang** [comment]
@tim-weis Thank you for your reply.

> This was a recent change (#3111). This now matches the Rust standard handle type [`std::os::windows::raw::HANDLE`](https://doc.rust-lang.org/std/os/windows/raw/type.HANDLE.html).

Thanks for that information. And, my idea is that the `HWND`, `HANDLE` and all these should be thread safe, right? So, can `windows-rs` unsafe impl `Send + Sync` for them, so I dont have to impl myself?
