### ISSUE TITLE
Race condition in WIA

### ISSUE THREAD

**Issue by zaaarf** [microsoft/windows-rs#3211]
### Summary

Hello! I have noticed a pretty nasty bug. The attached code will crash at the `let result = ...` line.

The reason for this appears to be that if no time passes between the declaration of the task (i.e. `ScanFilesToFolderAsync`) and the `get` call (specifically, the `Status` polling that happens underneath right at the start of that function), it will throw an error as the async task has not started yet. Specifically, this seems to happen only for `IAsyncOperationWithProgress`. 

As a workaround, I noticed I can just have the thread sleep for one millisecond and it will work, but obviously this is not ideal. This seems indicative of a race condition, though that's just a guess of mine since I'm not too sure of how the C code actually works under it all.

### Crate manifest

```TOML
[package]
name = "wia-test"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.58", features = ["Devices_Enumeration", "Devices_Scanners", "Storage_Streams", "Foundation_Collections"] }
```

### Crate code

```Rust
use windows::{
	core::HSTRING,
	Devices::{
		Enumeration::DeviceInformation,
		Scanners::ImageScanner
	}, Storage::StorageFolder
};

fn main() {
	let device_name = "YOUR DEVICE HERE";
	let info = DeviceInformation::FindAllAsync().expect("find all async failed").get().expect("async fail?");
	let mut id = None;
	for i in info {
		if i.Name().expect("failed to get name") == device_name {
			id = Some(i.Id().expect("failed to get id"));
		}
	}

	let id = id.expect("failed to find specified device");

	let scanner = ImageScanner::FromIdAsync(&id).unwrap().get().expect("failed to get scanner");


	let cwd = std::env::current_dir().expect("failed to get cwd").to_string_lossy().to_string();

	let folder_hstring = HSTRING::from(&cwd);
	let storage_folder = StorageFolder::GetFolderFromPathAsync(&folder_hstring).expect("bad path").get().unwrap();
	let source = scanner.DefaultScanSource().expect("failed to get default scan source");


	let task = scanner.ScanFilesToFolderAsync(
		source,
		&storage_folder
	).expect("failed to scan");

	//std::thread::sleep(std::time::Duration::from_millis(1)); // uncomment this and it will work
	let result = task.get().expect("unexpected async");
}
```

**Comment by kennykerr** [comment]
I'm not sure who owns that API (@jonwis) but WinRT async execution is hot-start meaning if `Status` returns something other than `Started` then it means that it has already run its course, successfully or otherwise. If you're observing something other than this then there may be a bug in the API implementation.

**Comment by kennykerr** [comment]
Your repro is not very practical since it presumably requires that I find a scanner. 😊 

> The stuff I mentioned about Status happens in your code, not in mine.

Keep in mind that there are really three parties involved here:

* Your code
* The `windows` crate
* The implementation of `IAsyncOperationWithProgress`

In other words, the `windows` crate is just the middleman. The `windows` crate defines the `get` method as follows:

https://github.com/microsoft/windows-rs/blob/623b678938c2a3c4e77870a29701102fbe4fed89/crates/libs/windows/src/extensions/Foundation/Async.rs#L261-L274

If the `Status` is `Started` then the calling thread goes to sleep waiting for completion. If the status is something other than `Started` then `GetResults` is called immediately because that's what the `IAsyncXxx` contract dictates. 

> This is not a "question": I've already found a workaround. The thing is, it shouldn't need one. It's a bug.

I'm not saying it's not a bug. I'm suggesting that you have not shown this to be a bug in the `windows` crate. 

It might be interesting to sidestep `get` and just call `Status` followed by `GetResults` directly, tracing out the results of both. That may tell you more about what is going on here.

**Comment by riverar** [comment]
Tip: Use `ImageScanner::GetDeviceSelector` to obtain an advanced query syntax (AQS) filter. This filter can be passed into `DeviceInformation::FindAllAsyncAqsFilter` to avoid retrieving thousands of devices unnecessarily.

The `.get()` method in this sample returns `E_ASYNC_OPERATION_NOT_STARTED`, which was very surprising to me. This might indicate an issue with the implementation in `Windows.Devices.Scanners.dll` or the broader WRL wrapper (!), rather than the crate itself. Perhaps @kennykerr or @jonwis can dig deeper / file an internal bug.

Tip: To make your workaround more reliable, consider calling `.get()` in a loop when `E_ASYNC_OPERATION_NOT_STARTED` is returned. You might use a helper function like this:

```rust
fn get_async<T, P>(task: &IAsyncOperationWithProgress<T, P>) -> windows::core::Result<T>
where
    T: windows_core::RuntimeType, // Note required windows_core dependency
    P: windows_core::RuntimeType,
{
    loop {
        match task.get() {
            Ok(value) => return Ok(value),
            
            // Impl. note: I was impatient and didn't immediately look into
            // why E_ASYNC_OPERATION_NOT_STARTED is missing.
            //                                 ↓
            Err(e) if e.code() == HRESULT(0x80000019u32 as _) => {
                std::thread::yield_now();
                continue;
            }
            Err(e) => return Err(e),
        }
    }
}
```

**Comment by kennykerr** [comment]
I had a quick look at the implementation (`onecoreuap/printscan/imaging/winrt/core/lib/ScanResult.cpp`) and it seems to be buggy and accounts for the observed behavior. As I mentioned above, WinRT async execution is hot-start so this should never leak out to the caller but in this case the implementation only transitions to the `Started` state by calling WRL's protected `Start` method inside the worker thread callback and so it's possible that the caller sees this "not started" state as it races ahead of the worked thread which may not execute immediately. So that confirms that this is a bug in the implementation.

**Comment by kennykerr** [comment]
For completeness, I reported this issue to the owner of this API.
