### ISSUE TITLE
`Param<PCSTR>` and `Param<PCWSTR>` could support more Rust Standard Library types

### ISSUE THREAD

**Issue by kennykerr** [microsoft/windows-rs#3254]
### Suggestion

Related to #3238, it could be possible to implement these traits for types like `&str`, `Path`, and `OsStr` to make it easier to call Windows APIs without requiring unintuitive conversions.

**Comment by kennykerr** [comment]
I had a look at this but the underlying `ParamValue` that is packed onto the stack doesn't have this capability and adding it would mean these would all get `Drop` implementations which would likely bloat call sites significantly.

**Comment by Nordgaren** [comment]
Yea, I think `&CStr` would work really well for `A` methods, and it would also allow `CString` to be somewhat compatible, since you can use a reference to a `CString` as a `&CStr`, like a `String` and `&Str`

**Comment by tim-weis** [comment]
There's a tradeoff between offering ergonomic interfaces and promoting ill-advised code patterns. Automatic conversions from `&CStr` to `PCSTR` fall into both categories and the decision has to be made based on which one weighs stronger. It is my opinion that it is the latter.

As Kenny mentions, calling the ANSI variant of an API generally involves the appropriation of an internal buffer and a translation between character encodings. This is problematic for several reasons:

* Dynamic allocation is costly and can fail.
* If the API uses a static buffer instead it can fail due to arbitrary limits (such as `MAX_PATH`).
* Translation between character encodings isn't free even when nowhere near as costly as an allocation.
* Translation makes implicit assumptions about the source character encoding which may not coincide with the concrete source character encoding.
* In addition translation is also performed on output parameters, leading to further failure modes and mismatched assumptions about the target character encoding.

Hiding those issues behind an automatic conversion doesn't feel right. If nothing else, the absence of the requested automatic conversions at the very least somewhat pulls problematic code out of complete stealth. I'd rather have bad code look bad.

**Comment by Nordgaren** [comment]
-     Dynamic allocation is costly and can fail.
This is going to happen when a user passes in a an ascii c string, regardless to the function, no?

-     If the API uses a static buffer instead it can fail due to arbitrary limits (such as MAX_PATH).
Then it sets GLE and passes back null, right?
-     Translation between character encodings isn't free even when nowhere near as costly as an allocation.
But this has to happen regardless. Even if I use HSTRING, because if I am reading data that contains C strings, I will have to convert them to HSTRING. 
-     Translation makes implicit assumptions about the source character encoding which may not coincide with the concrete source character encoding.
Won't this cause the API function to fail, set GLE and return?
-     In addition translation is also performed on output parameters, leading to further failure modes and mismatched assumptions about the target character encoding.
I am kinda confused by this. `PCSTR` is not mutable, so, how would this allow for the buffer to be used in a mutable context? Or do you mean output parameters that are transformed based on the input?

`&CStr` is there so the user can interact with c style strings. It's just a reference and length of existing c style string. If I want to iterate over some c style strings, like a lot of your APIs might have me do, and I want to examine them in any way, to determine if I should call an API, I need to use `CStr`. I don't really have any other options in Rust. Since PCSTR is a newtype *const u8, this makes for an annoying conversion from `CStr::as_ptr()`, as that gives a c_char.

If I am using windows::core::Result<()> for a safe wrapper around a windows API call that validates everything for the caller, now I have to match or do something else with the `.as_str()` function on CStr, as you don't implement `From<Utf8Error>` on the windows Result type.

I kinda see where you are coming from that there can be failures, but, what would you suggest, if I wanted to use c style strings from c data, check some bytes in the string, to see if it's what I am looking for, and then call a windows API function? If I start passing `PCSTR(string.as_ptr())` to windows functions, isn't that also bad code? I can't always use `s!()` when using ascii api, as that's only compile time. Really the only good way in Rust to do strings at Runtime is with `CString` and if you are using c data or c api calls and getting pointers, then `CStr`.

Otherwise, I don't think any other utf8 string in Rust should be used with C String. Not even `OsString`, because it's not null terminated.

**Comment by Nordgaren** [comment]
![image](https://github.com/user-attachments/assets/9cc8d84f-0b35-4627-ada4-93b8bcc58a80)
🤔

**Comment by 0xTriboulet** [comment]
I concur with Nordgaren's comments here https://github.com/microsoft/windows-rs/issues/3254#issuecomment-2337091113

`calling the ANSI variant of an API generally involves the appropriation of an internal buffer and a translation between character encodings`

The above is true, but as is the case with `OutputDebugStringW` there are cases where `A`->`W` translation happens as well in a manner transparent to the developer. Given that both `A`->`W` and `W`->`A` translations are liable to happen during a API call, it seems that the concern is out of scope if considering a more intuitive Rust interface.

In my opinion, the reality is that forcing unintuitive interaction with the already unsafe wrappers is a headache that, at minimum, disuades developers from adopting Rust on Windows. I think streamlining interactions between Rust types and requisite WinAPI types is key to increasing adoption, and ultimately improving the memory safety of Windows applications

**Comment by Porges** [comment]
Now that we've had C-string literals for a year it'd be really nice to be able to pass them natively.
