### ISSUE TITLE
`ShellExecuteW()` (and `...A()`) should be `#[must_use]`

### ISSUE THREAD

**Issue by Enyium** [microsoft/windows-rs#3309]
### Summary

The [docs page](https://learn.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shellexecutew#return-value) shows that there may be many errors encoded in an `HINSTANCE`. Like a `Result`, which is also `#[must_use]`, the user should get a warning to be hinted to handle the errors.

**Comment by tim-weis** [comment]
This information isn't available from the metadata driving the code generator so it cannot apply the `#[must_use]` attribute.

A better approach is to avoid calling `ShellExecute[A|W]` altogether due to the multitude of issues surrounding it (its signature strongly suggests that this is a holdover from 16-bit Windows). [`ShellExecuteExW`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/UI/Shell/fn.ShellExecuteExW.html) is an all-around improved version. This includes consistent error reporting that the `windows` crate relies on to apply the `Result<>` transformation.

**Comment by Enyium** [comment]
> A better approach is...

Approach? You're telling me this now. But others intending to use the function won't see your comment about it. From my practical perspective, `ShellExecuteW()` is preferrable because of its simplicity, and its docs page doesn't recommend `ShellExecuteExW()` over it.

> This information isn't available from the metadata driving the code generator so it cannot apply the `#[must_use]` attribute.

I read this as it also won't be implemented. So, closing the issue, and trying to remember `#[must_use]` is never addable.
