### ISSUE TITLE
`x86_64-win7-windows-msvc` target support

### ISSUE THREAD

**Issue by nikvoid** [microsoft/windows-rs#3388]
### Suggestion

Is there a way to compile these crates for Windows 7 target?

**Comment by kennykerr** [comment]
That's not something I've tried but I don't know of anything specifically that prevents this. Still, Windows 7 support is not something we'd specifically support.

**Comment by jcm93** [comment]
Hello; just wanted to point out at least one breakage on Windows 7- the use of `RoOriginateErrorW` [here](https://github.com/microsoft/windows-rs/blob/c8616a4fd8ce0856fe5b289ee104c3547ca53bb0/crates/libs/result/src/error.rs#L303).

I'm not sure if there may be other breakages or if that's the only one. I also don't want to campaign strongly for Windows 7 support or anything; I just figured it was better to report it than not, since we ran into this a couple layers downstream when trying some experimental Windows 7 testing.
