### ISSUE TITLE
Reduce dependency on transmute

### ISSUE THREAD

**Issue by kennykerr** [microsoft/windows-rs#357]
https://github.com/microsoft/winrt-rs/pull/354#discussion_r525957262

**Comment by fghzxm** [comment]
```rust
use core::ptr::NonNull;

pub unsafe fn f<'a>(ptr: *mut u8) -> &'a mut u8 {
    NonNull::new_unchecked(ptr).as_mut()
}
```
[produces](https://rust.godbolt.org/z/fx6r5P)
```
error[E0515]: cannot return value referencing temporary value
 --> <source>:4:5
  |
4 |     NonNull::new_unchecked(ptr).as_mut()
  |     ---------------------------^^^^^^^^^
  |     |
  |     returns a value referencing data owned by the current function
  |     temporary value created here
```
This is because `core::ptr::NonNull::<T>::as_mut` [has signature](/rust-lang/rust/blob/ed58a2b03b6284b070fae2349898b16df98b7765/library/core/src/ptr/non_null.rs#L283)
```rust
   unsafe fn as_mut(&self) -> &mut T
// -----------------^---------^-----
// should be unsafe fn as_mut<'a>(self) -> &'a mut T
```
which contradicts its claim to produce a reference of arbitrary lifetime.  Should we contact rust-lang/rust?

**Comment by kennykerr** [comment]
Closing this issue. Transmute is necessary in some cases. Feel free to create new issues for specific cases where you may feel we can improve.
