### ISSUE TITLE
Add WebView2 sample

### ISSUE THREAD

**Issue by kennykerr** [microsoft/windows-rs#538]

**Comment by wusyong** [comment]
Hello I would like to help. But I couldn't find any types/structs in the generated docs. Is there any extra step need to do?

**Comment by kennykerr** [comment]
The WebView2 component is not included in the Windows API as it is shipped separately:

https://www.nuget.org/packages/Microsoft.Web.WebView2

You can download the nuget package (it's just a zip file) and extract the DLLs and winmd file. There are two APIs, a WinRT API described in the winmd and a COM API described in IDL.

You should already be able to use the WinRT API with the `windows` crate but I am also exploring options for importing the COM API by converting it to a winmd first.

**Comment by wravery** [comment]
I've been experimenting with this, starting from a forked branch of [webview/webview_rust](https://github.com/webview/webview_rust): https://github.com/wravery/webview_rust/tree/windows-rs. It uses a `build.rs` script to pull down the NuGet package automatically and [CXX](https://cxx.rs/) for a thin wrapper with 1:1 projections of the interfaces/methods/APIs. I got to the point where I was able to remove the `webview-official-sys` crate/submodule and all of the samples still ran.

I wanted to jump straight to `windows-rs` generated bindings, and I was able to hack together support for WebView2 in [microsoft/win32metadata](https://github.com/wravery/win32metadata/commit/6f9eb8e4946b9fa4a9b2071d2490b73e50d7f266), but I wasn't able to generate usable results with that and the current version of `windows-rs`. WebView2 requires _implementing_ a lot of COM interfaces for callbacks and such. #429 The CXX bindings I wrote are a small sub-set of what WebView2.h includes, and they're meant to replicate what I think `windows-rs` might generate, because eventually I want to throw it out and auto-generate it.

It also uses UTF-16 `PCWSTR` throughout instead of UTF-8. Since I needed to implement my own bindings module for this library, and Rust already has support for conversion back and forth, I decided not to use `MultiByteToWideString`/`WideToMultiByteString` from `windows-rs`. I wrote my own safe utility functions to convert from `String`/`&str` back and forth to `Vec<u16>`/`&[u16]`. If I were just using `windows-rs` I might do the same thing, it would be really handy to have implementations of `From`/`Into` for wide string types built-in to windows-rs. #645

@wusyong, coincidentally the next step in the experiment would have been to try injecting it in [Tauri](https://github.com/tauri-apps/tauri), but I noticed too late that your [tauri-apps/wry](https://github.com/tauri-apps/wry) component replaced [webview/webview_rust](https://github.com/webview/webview_rust). It looks much nicer to me than the [webview/webview_rust](https://github.com/webview/webview_rust) bindings, even if it does mean I need to change directions. :smile: So instead, I'll try building a separate crate with just my bindings (the replacement for `webview-official-sys`) and see if I can wrap that in a look-alike API to the [sopium/webview2](https://github.com/sopium/webview2) crate you're using right now. There's nothing wrong with that implementation, my only goal is to experiment with `windows-rs` + WebView2.

**Comment by kennykerr** [comment]
Thanks for experimenting! Note also that WebView2 ships with both a COM and a WinRT API and they largely provide the same functionality. You may have better luck with the WinRT API in the short term. I am now starting to focus on #81 which includes implementing COM interfaces so eventually you'll be able to use either API.

**Comment by wravery** [comment]
I think the `.winmd` was included in a previous version of WebView2 by accident, or maybe it just broke something and will be re-added: https://github.com/MicrosoftEdge/WebView2Feedback/issues/668. It was removed in the latest version of the package though, at least in the release version (1.0.774.44)[https://docs.microsoft.com/en-us/microsoft-edge/webview2/releasenotes#1077444]. I haven't found a way to use the WinRT API without falling back to the older package.

**Comment by kennykerr** [comment]
It's available in the latest prerelease: https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.824-prerelease

**Comment by wravery** [comment]
Thanks, I found your https://github.com/kennykerr/webview2-rs repo, and I was able to re-build my `windows-rs` bindings based on that with the latest pre-release `.winmd`. I'll see if I can get the samples working again based on the WinRT bindings, that would certainly simplify the implementation.

I'm not sure, but I think I'll still need a Win32 message loop and parent HWND. This should mean I don't need the CXX bindings, and a lot of the unsafe windows::win32 code other than that can go too. If I simplify it a bit and cleanup the dependencies, I may make a PR resolving this issue by adding a working barebones example.

**Comment by kennykerr** [comment]
Yes, you'll still need a desktop window. You can copy that code from here if you need a head start:

https://github.com/microsoft/windows-rs/blob/master/examples/clock/src/main.rs

Thanks!

**Comment by wravery** [comment]
It's working. :smile: Now I just need to boil it down to a simpler sub-project to add to the examples.

**Comment by kennykerr** [comment]
Woohoo, can't wait to see it! 🙃
