### ISSUE TITLE
HWND could implement the Hash trait

### ISSUE THREAD

**Issue by emmanuelantony2000** [microsoft/windows-rs#589]
`win32::windows_and_messaging::HWND` could implement the `Hash` trait.

**Comment by tim-weis** [comment]
The Rust API Guidelines lists the most common traits ([C-COMMON-TRAITS](https://rust-lang.github.io/api-guidelines/interoperability.html#c-common-traits)) to implement. These are:

* `Copy`
* `Clone`
* `Eq`
* `PartialEq`
* `Ord`
* `PartialOrd`
* `Hash`
* `Debug`
* `Display`
* `Default`

I would suggest implementing all of those, particularly for new-type wrapper types, unless there is a striking reason not to.

**Comment by kennykerr** [comment]
This is a little challenging because many structs cannot necessarily implement all of these traits due to language restrictions. Others require specialized code. For example, unions and packed structs pose unique challenges. For those where it is permitted, it can be costly to derive some of these. I'm in favor of providing as many of these as possible, just identifying some of the  reasons why this isn't as simple as it might seem.

**Comment by kennykerr** [comment]
The `windows-sys` crate implements `Copy` and `Clone` (the minimal required) while the `windows` crate implements a few more as applicable. Let me know if additional are required, but I'd like to avoid adding implementations just because "it would be nice to have" as it hurts compile time for so many types.
