### ISSUE TITLE
MAKEINTRESOURCE seems to be missing

### ISSUE THREAD

**Issue by Samuel-B-D** [microsoft/windows-rs#641]
I'm not quite sure how I could be using `bindings::windows::win32::windows_and_messaging::LoadIconA` without the `MAKEINTRESOURCE`. The relevant constants like `bindings::windows::win32::windows_and_messaging::IDI_APPLICATION` are exposed, but how to make use of them without `MAKEINTRESOURCE`?

**Comment by kennykerr** [comment]
There's an open issue discussing how to deal with this here: https://github.com/microsoft/win32metadata/issues/69

`MAKEINTRESOURCE` is basically just a Rust `transmute` operation so that in itself isn't too difficult to work around. `IDI_APPLICATION` is defined as `32512` cast to `PSTR`. 

I also have an issue open to make the definition of constants like `IDI_APPLICATION` correctly typed so that you can just pass the constant to `LoadIconA` directly: https://github.com/microsoft/windows-rs/issues/631

**Comment by Samuel-B-D** [comment]
Gotcha, `PSTR(IDI_APPLICATION as *mut u8)` is working.
