### ISSUE TITLE
Keep public API and documentation in sync

### ISSUE THREAD

**Issue by tim-weis** [microsoft/windows-rs#657]
A [recent pull request](https://github.com/microsoft/windows-rs/pull/651) highlighted a disconnect between the public API and the public-facing [documentation](https://crates.io/crates/windows) (probably outdated now).

Specifically, the documentation visible on crates.io is a direct copy of the [readme.md](https://github.com/microsoft/windows-rs/blob/master/readme.md) file of this repository on the *master* branch.

It'd be nice to have the documentation and API in sync. For my personal projects I'm using a trimmed-down version of [A successful Git branching model](https://nvie.com/posts/a-successful-git-branching-model/), where the *master* branch reflects all public artifacts, and development being done on a different branch (like *develop*).

Would something like this be feasible for this repository as well to close the gap between documentation and API realities?

**Comment by kennykerr** [comment]
I'm not sure there's a huge need for a more interesting branching system at the moment. I'm aiming for weekly releases on crates.io and it's unusual to have such a breaking change. As it is, I published [0.7.0](https://crates.io/crates/windows) this morning and the [crate docs](https://docs.rs/windows/0.7.0/windows/) and [API docs](https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/) are already up to date. 

Thanks for responding to that issue! In general I like to keep everything that crates.io points to up to date and consistent with the latest published version. As you surmised, what appears on GitHub is what is accumulating for the next published version. It's useful for this to be in master so that early adopters can flush out any issues before the next release.
