### ISSUE TITLE
DWORD, LPVOID missing from Windows::Win32::Foundation

### ISSUE THREAD

**Issue by cedws** [microsoft/windows-rs#881]
Was just looking at whether I would be able to use this instead of `winapi`. However, `DWORD` and `LPVOID` are missing from the `Foundation` module. I'm unsure if this is an oversight or there is a good reason for this.

**Comment by kennykerr** [comment]
Those are C typedefs for primitive types that the [win32 metadata](https://github.com/microsoft/win32metadata) does not define. Instead it simply uses the underlying types directly. So `u32` instead of `DWORD` and so on. 

But in many cases, the win32 metadata is in fact far richer than the original C-style definitions. For example, compare the [CreateFileA](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilea) docs with the [definition in Rust](https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/Storage/FileSystem/fn.CreateFileA.html).

**Comment by cedws** [comment]
I see, thank you. So the options are to create a type alias or simply use the underlying type right?

**Comment by kennykerr** [comment]
Yep!

**Comment by cedws** [comment]
Great, thanks again.

**Comment by lostmsu** [comment]
While it is clear for `DWORD`, what is the Rust type that should be used for `LPVOID`?

**Comment by riverar** [comment]
@lostmsu `*const c_void` or `*mut c_void` ideally. `isize` in a pinch. May I ask what API you're working with?

**Comment by lostmsu** [comment]
@riverar just needed a signature for `DllMain`
