### ISSUE TITLE
Is there a way to support WebAssembly + Electron ?

### ISSUE THREAD

**Issue by dukesome** [microsoft/windows-rs#906]
Is there a way to support WebAssembly together with Electron?

I understand that the Windows API is not possible in being accessed from the Browser. But could that be possible from an Electron environment instead ?

I tried to run a minimal example and got the following errors:

```
Uncaught (in promise) RuntimeError: unreachable
    at hello_wasm_bg.wasm:0x3154
    at hello_wasm_bg.wasm:0x3319
    at hello_wasm_bg.wasm:0x3889
    at hello_wasm_bg.wasm:0x37fb
    at hello_wasm_bg.wasm:0x38be
    at hello_wasm_bg.wasm:0x3485
    at greet_from_win (hello_wasm_bg.wasm:0x36d8)
    at greet_from_win (hello_wasm.js:89)
    at index.html:19
```
(This is the same error you would get if you were to try to run that in the Browser)

where the rust code looks just like this:
```
use wasm_bindgen::prelude::*;
use bindings::{
    Windows::Win32::UI::WindowsAndMessaging::{MessageBoxA, MB_OK},
};

#[wasm_bindgen]
pub fn greet_from_win(name: &str) {
    unsafe {
        MessageBoxA(None, name, "Hello World", MB_OK);
    }
}
```

**Comment by kennykerr** [comment]
I'm sorry I don't know anything about WebAssembly/Electron.

**Comment by XiNiHa** [comment]
How about trying Node-API based solution? (https://github.com/napi-rs/napi-rs)
It seems possible to load an Node-API addon from the main process(not the renderer) and then communicate with renderer processes using IPC tools provided. Not sure if `napi-rs` crate supports `windows` create but it looks worth trying.

**Comment by rylev** [comment]
This crate enables the use of Windows APIs anywhere they are supported. WebAssembly runs in a sandboxed (VM-like) environment that only has access to the outside world through allow-listed APIs that users of the VM enable. This is typically either JavaScript APIs (in the case of the browser) or interfaces to native host APIs (in the case of WASI). So, in short, this crate cannot be used from WebAssembly because WebAssembly *by design* does not allow access to the host OS.

Electron uses Node.js to run a process on the host machine and Node can interact with the OS it's running on using napi over a C FFI boundary. In that case, since Node can execute arbitrary code, this crate can be used to interact with Windows APIs (of course only when running on Windows). I've not used `napi-rs` but that seems like a good suggestions.
