### ISSUE TITLE
Structs that hold pointers to arrays of structs should have lifetime parameters

### ISSUE THREAD

**Issue by damyanp** [microsoft/windows-rs#907]
For example:

```c++
typedef struct D3D12_ROOT_DESCRIPTOR_TABLE
    {
    UINT NumDescriptorRanges;
    _Field_size_full_(NumDescriptorRanges)  const D3D12_DESCRIPTOR_RANGE *pDescriptorRanges;
    } 	D3D12_ROOT_DESCRIPTOR_TABLE;
```

pDescriptorRanges points to the start of an array of NumDescriptorRanges D3D12_DESCRIPTOR_RANGE instances.  The generated rust type should have an appropriate lifetime parameter indicate that this array must be valid for as long as the D3D12_ROOT_DESCRIPTOR table instance is valid.

This pattern exists across many D3D12 structs, and possibly in other Win32 ones as well.

**Comment by damyanp** [comment]
Currently, win32metadata does not include anything associating these two fields together, so it is likely some work will be required there. I think we need to agree that including these lifetime parameters is the right thing to do, figure out what metadata is required and get the appropriate issue filed.  Once that's done we'll be able to do the windows-rs work to resolve this issue.

**Comment by kennykerr** [comment]
Sweet, thanks for opening the issue. I have other issues open for supporting arrays in general, which I currently only support minimally, but this will be useful to track this specific pattern. 

We'll need another issue on the win32metadata repo for adding metadata to account for the `_Field_size_full_(NumDescriptorRanges)` SAL annotation. The metadata already parses SAL annotations so that shouldn't be a problem - we just need to get them to add this one somehow.

**Comment by kennykerr** [comment]
Other array-related issues: #212 #443 #479 #790

I hope to address all of these together when I get a moment.

**Comment by kennykerr** [comment]
Doesn't look like there's been any progress metadata issue. https://github.com/microsoft/win32metadata/issues/547

I'll close this issue for now but keep an eye on that metadata issue. If that is resolved, we can revisit this.

**Comment by stormshield-gt** [comment]
Hi, sorry for commenting on old issue, the meta issue has been closed https://github.com/microsoft/win32metadata/issues/547 so maybe we can revisit this one ?
