### ISSUE TITLE
Refer to create_instance in CoCreateInstance documentation

### ISSUE THREAD

**Issue by saschanaz** [microsoft/windows-rs#980]
Doing so will help users learn the easier helper function exists. 👍

**Comment by kennykerr** [comment]
I assume you mean this documentation?

https://github.com/microsoft/windows-docs-rs (repo)
https://microsoft.github.io/windows-docs-rs (docs)

This is simply generated from metadata and there is no way currently to add hand-written documentation although there are a few issues for improving docs including #931 #851 #546

At this point that documentation is just an experiment and I'm not yet sure where to go with it. Cargo docs doesn't really scale to the sheer size of the Windows API so I'm not sure whether it is a useful approach long term. 

Happy to hear your thoughts.

**Comment by saschanaz** [comment]
Yes, the docs-rs page is my reference for everything so I would be happy if there is a way to notify the existence of helpers for certain raw functions.

**Comment by kennykerr** [comment]
Actually, with the work I've recently done to simplify many COM functions and method callsites, I think I'll probably remove the helpers I originally added to the Windows crate entirely since they add little value and aren't particularly discoverable or maintainable. I'd rather the Windows crate focus on providing the highest quality API bindings and let other crates come along and support specific APIs in more idiomatic ways (once #432 lands).
